### ISSUE TITLE
Problems after upgrade to 2010.10.1

### ISSUE THREAD

**Issue by tangix** [Thomas55555/husqvarna_automower#114]
(I'm still running HAOS 2021.9.7)
I upgraded the automower module and got this error message:
```
Failed to set up: Your API-Key is not compatible to websocket, please renew it on https://developer.husqvarnagroup.cloud/
```
Tried to renew the API key on Husqvarna portal and ran the curl test with success. Still no go with the integration.

Created a new Application, added AutoMower and Authentication APIs and got the following problems:
```
Make sure that the Authentication API and the Automower-Connect API is connected with your API-Key: https://developer.husqvarnagroup.cloud/
```

Any ideas?

**Comment by tangix** [comment]
Still same error, even with the new Application key:
`Make sure that the Authentication API and the Automower-Connect API is connected with your API-Key: https://developer.husqvarnagroup.cloud/`
Running the `curl` example for Husqvarna site works and gives `,"scope":"iam:read amc:api"` in the response.
Note - I'm still on HAOS 2021.9.7 and a bit reluctant to upgrade to 2021.10 just yet...

**Comment by tangix** [comment]
Can't find much in the logs:
```
2021-10-14 18:09:18 DEBUG (MainThread) [aioautomower.rest] Resp.status get access token: 200
2021-10-14 18:09:18 DEBUG (MainThread) [aioautomower.rest] Resp.status mower data: 403
```

**Comment by tangix** [comment]
![image](https://user-images.githubusercontent.com/1013635/137359116-0d5581e1-a833-40c0-80ca-df2d830bf62b.png)

**Comment by Thomas55555** [comment]
@simontegelid: I don't see an indication for that in the logs above. I think it's better to check if the basic functionality of the integration is already working in the config flow. What can you do with an integration, that gives you an "unavailable" entity? And the question is, why the data should be retrieved later, when it's not working in the config flow. The response should still be `200` and the metadata should show something like `'metadata': {'connected': False, 'statusTimestamp': 1634202375564}`, even if the mower is "BORTKOPPLAD". But maybe we can see if the websocket works in this special case, if @tangix can help us.
@tangix: Can you please comment out this lines with an `#` in your `./config/custom_components/husqvarna_automower/cnfig_flow.py`?
https://github.com/Thomas55555/husqvarna_automower/blob/c1c09003019baf5e9ba86078d417564b48c37394/custom_components/husqvarna_automower/config_flow.py#L67-L82

Save it, and than restart your home assistant and try it again?

**Comment by Thomas55555** [comment]
As I said, even if the mower itself is not accessible, the API should still send an status like `Connected: False`. There must be something else wrong, But I have no idea, what it can be.

**Comment by simontegelid** [comment]
I just experienced this myself and it's not related to the API key. Passing the stored token in the HASS config entry gives a 403 on the GetMowerData (no token refresh is performed since the token is still not expired). I also tried to refresh the token if the GetMowerData fails, but that gives `aioautomower.rest.TokenRefreshError: The token cannot be refreshed, respone from Husqvarna Automower API: 400`. It works just fine to use username/password (with the same API key) to get a new token. Storing that new token and passing later on also works fine.

I modified the CLI in aioautomower to take an optional token as input and use that for login instead of username/password, will push that as as debug tool for this.

Reopening this.

**Comment by tangix** [comment]
The mowing season is soon over in the Northern Hemisphere but starts in the Southern so you'll have plenty of user feedback to help troubleshoot this! Our mower has worked since I recreated the Application Keys but I don't know the timeout
Keep up the great work with this integration!

**Comment by etskinner** [comment]
> Can you please check, if your new token is really connected to both of the APIs? I have no other explanation right now.

This fixed the issue for me. I connected all the available APIs
- GARDENA smart system API
- Authentication API
- Automower Connect API

Before that, I had the same issue:

`Make sure that the Authentication API and the Automower-Connect API is connected with your API-Key: https://developer.husqvarnagroup.cloud/`

After that, it authenticated successfully and added my mower as a device.
