### ISSUE TITLE
Headlight mode is not updating

### ISSUE THREAD

**Issue by Thomas55555** [Thomas55555/husqvarna_automower#135]
I've noticed, that the new feature for setting the headlight mode is only updating, after a HA restart. Same for the Android Automower App: I have to restart it, to see the changes in the headlight mode. Right now, not sure, why it is like that.

**Comment by simontegelid** [comment]
The websocket is only updating substructures of the whole dataset, it might be so that the websocket task need some updates to update the headlights. Or the headlight status isnt sent over websocket. @Thomas55555 can you paste a REST response with the initial data including headlight data?

**Comment by Thomas55555** [comment]
The headlight status isn't sent over websocket. I will ask husqvarna for that.

**Comment by simontegelid** [comment]
Ok, maybe we should add a REST data polling thing every 10 mins or so in aioautomower to refresh all data as a fallback in case websockets stop working and to catch these things

**Comment by Thomas55555** [comment]
But just to make it complete, here is the Rest response:
```
{'data': [{'type': 'mower', 'id': 'b2bc3443-b31a-4c7f-834e-d6e408c53f1b', 'attributes': {'system': {'name': 'Haffi', 'model': 'HUSQVARNA AUTOMOWER® 315X', 'serialNumber': 181309473}, 'battery': {'batteryPercent': 70}, 'mower': {'mode': 'HOME', 'activity': 'NOT_APPLICABLE', 'state': 'STOPPED', 'errorCode': 0, 'errorCodeTimestamp': 0}, 'calendar': {'tasks': [{'start': 300, 'duration': 360, 'monday': False, 'tuesday': True, 'wednesday': False, 'thursday': False, 'friday': False, 'saturday': False, 'sunday': False}]}, 'planner': {'nextStartTimestamp': 0, 'override': {'action': 'NO_SOURCE'}, 'restrictedReason': 'NOT_APPLICABLE'}, 'metadata': {'connected': True, 'statusTimestamp': 1636056062537}, 'positions': [{....all the positions...}], 'settings': {'cuttingHeight': 1, 'headlight': {'mode': 'EVENING_AND_NIGHT'}}}}]}
```
and here the settings-event:
```
{'id': 'b2bc3443-b31a-4c7f-834e-d6e408c53f1b', 'type': 'settings-event', 'attributes': {'calendar': {'tasks': [{'start': 300, 'duration': 360, 'monday': False, 'tuesday': True, 'wednesday': False, 'thursday': False, 'friday': False, 'saturday': False, 'sunday': False}]}}}
````

**Comment by simontegelid** [comment]
Ok, [their docs](https://developer.husqvarnagroup.cloud/apis/Automower+Connect+API#/websocket) says that headlight should be part of the settings-event:
> When cutting height or headlight is updated. json { "id": "f6d368e8-9312-49ee-9fce-dc1aa1a54910", "type": "settings-event", "attributes": { "cuttingHeight": 5, "headlight": { "mode": "ALWAYS_ON" } } }

**Comment by Thomas55555** [comment]
Yes, I'm still waiting for an answer of husqvarna.

**Comment by Thomas55555** [comment]
I didn't get an answer, but tested it today again. Now there is an response:
```
2021-11-09 17:32:02 DEBUG (MainThread) [aioautomower.rest] Mower Action URL: https://api.amc.husqvarna.dev/v1/mowers/b2bc3443-b31a-4c7f-834e-d6e408c53f1b/settings
2021-11-09 17:32:02 DEBUG (MainThread) [aioautomower.rest] Sent payload: {"data": {"type": "settings", "attributes": {"cuttingHeight": 1, "headlight": {"mode": "EVENING_AND_NIGHT"}}}}
2021-11-09 17:32:02 DEBUG (MainThread) [aioautomower.rest] Resp status mower command: 202
2021-11-09 17:32:02 DEBUG (MainThread) [aioautomower.session] Received TEXT
2021-11-09 17:32:02 DEBUG (MainThread) [aioautomower.session] {'id': 'b2bc3443-b31a-4c7f-834e-d6e408c53f1b', 'type': 'settings-event', 'attributes': {'calendar': {'tasks': []}, 'headlight': {'mode': 'EVENING_AND_NIGHT'}}}
2021-11-09 17:32:02 DEBUG (MainThread) [aioautomower.session] Got settings-event
2021-11-09 17:32:02 DEBUG (MainThread) [aioautomower.session] Schedule data callback <function HusqvarnaAutomowerEntity.__init__.<locals>.<lambda> at 0x7f89cd777430>
2021-11-09 17:32:02 DEBUG (MainThread) [aioautomower.session] Schedule data callback <function AutomowerTracker.__init__.<locals>.<lambda> at 0x7f89cd7090d0>
2021-11-09 17:32:02 DEBUG (MainThread) [aioautomower.session] Schedule data callback <function AutomowerSelect.__init__.<locals>.<lambda> at 0x7f89cd709670>
```
But it doesn't update the select entity. Instead of `self._attr_current_option` in the `select.py` I also tried it with a property:
```
    @property
    def current_option(self) -> str:
        """Return a the icon for the entity."""
        mower_attributes = self.__get_mower_attributes()
        _LOGGER.debug(
            "Current option: %s", mower_attributes["settings"]["headlight"]["mode"]
        )
        return mower_attributes["settings"]["headlight"]["mode"]
```
But it always returns just this:
```
2021-11-09 17:36:32 DEBUG (MainThread) [custom_components.husqvarna_automower.select] Current option: EVENING_ONLY
```
`EVENING_ONLY` was the mode selected before.

**Comment by Thomas55555** [comment]
Okay, found something out. That's part of the first return of REST at startup:
`'settings': {'cuttingHeight': 1, 'headlight': {'mode': 'ALWAYS_ON'}}`
Later if I look into `self.session.data["data"]`, I can see this:
`'settings': {'cuttingHeight': 1, 'headlight': {'mode': 'ALWAYS_ON'}}, 'cuttingHeight': 1, 'headlight': {'mode': 'EVENING_AND_NIGHT'}}}`
Is it our fault, that the substructure of the dataset is not updated correctly?
I tried this one, and then it is working perfectly:
```
    @property
    def current_option(self) -> str:
        """Return a the icon for the entity."""
        mower_attributes = self.__get_mower_attributes()
        try:
            test = mower_attributes["headlight"]["mode"]
        except KeyError:
            test = mower_attributes["settings"]["headlight"]["mode"]
        return test
```
But that can't be the goal.

**Comment by Thomas55555** [comment]
I think it's still husqvarnas fault.
They send:
`{'id': 'b2bc3443-b31a-4c7f-834e-d6e408c53f1b', 'type': 'settings-event', 'attributes': {'calendar': {'tasks': []}, 'headlight': {'mode': 'EVENING_AND_NIGHT'}}}`
But they should send:
`{'id': 'b2bc3443-b31a-4c7f-834e-d6e408c53f1b', 'type': 'settings-event', 'attributes': {'calendar': {'tasks': []}, 'settings': {'headlight': {'mode': 'EVENING_AND_NIGHT'}}}}`
Right?

**Comment by Thomas55555** [comment]
But otherwise it's exactly like in their docs....
