### ISSUE TITLE
Time not correct

### ISSUE THREAD

**Issue by yashijoe** [Thomas55555/husqvarna_automower#177]
Hi
schedule time from the automower app is 13.00 
while in home assistant it says 
Schedule, next start: Thu 14:00

Is there a way I can fix it?
Thanks a lot

**Comment by yashijoe** [comment]
> Can you install version 2022.3.0b and try, if it works?

Hello Thomas, thanks for support
Once installed the beta I got the message the the integration cannot be loaded.
Also tried to uninstall and reinstall repository but no result.
Once back on official release it’s back to standard working (with time bug)
Of course I’ve rebooted on each try.
Thanks

**Comment by Thomas55555** [comment]
Looks like the version key is not accepted. I've released another beta called 2022.3.0
Can you trie this one?

**Comment by yashijoe** [comment]
> Looks like the version key is not accepted. I've released another beta called 2022.3.0
> Can you trie this one?

It still doesn’t load the integration
