### ISSUE TITLE
Husqvarna integration keeps losing connection recently

### ISSUE THREAD

**Issue by denstech** [Thomas55555/husqvarna_automower#188]
Hi, I have messaged Thomas earlier. Husqv integration keeps losing connection since a few days ago. Nothing wrong with Robomower or cloud because native iPhone app has no problems. HomeAssis log lists 'token refresh' issues. 
I'm on HA Blue hub running HA core 2022.3.6 and HA OS 7.5

**Comment by denstech** [comment]
<img width="1000" alt="Husqvarna log for connection loss" src="https://user-images.githubusercontent.com/97118648/159761435-b2e8730d-1d68-4795-be1d-48167ed86e6c.png">

**Comment by Thomas55555** [comment]
Have you checked your notifications, if HA asks you, to re-authenticate the integration?

**Comment by denstech** [comment]
Do you mean the logs rather than notifications? There is nothing in notifications, only the logs. 
Do you suggest I delete and re-add the integration or just try to re-cofigure it again? What exact steps do you recommend?
I did a few reloads of the integration and I see from the logs that it consistently loses connection after about 25-28 minutes.

**Comment by Thomas55555** [comment]
Yes, I mean the notifications. They are in the lower left corner of the UI.
My suggestion only referred to the 400 error. If you did a re
authentication, then you did everything right. The problem, that the
connection is losing is related to the husqvarna websocket. Right now, it's
not working. So the mower becomes unavailable.
As the integration is using another API than the Android/iOS app, it's
working there, but not on home assistant.

denstech ***@***.***> schrieb am Mi., 23. März 2022, 21:41:

**Comment by denstech** [comment]
Ok I deleted the integration fully (both from Integrations and from HACS) and downloaded it again and set it up with the API key. It has found my robomower (Shelby) again but we'll have to see what happens next. Is the websocket a Husqvarna issue beyond our control or a HA issue? I'm not expert enough to know. Thanks for your messages so far.

**Comment by denstech** [comment]
So after a complete delete & re-download & re-config of the integration, connection was lost again after 27 mins. So as stated before, it only holds for 25-28 mins

**Comment by Thomas55555** [comment]
Yes, that sounds like the behaviour it should have, when the websocket is not working. But as you said, that's beyond our control. Unfortunately this integration relies on the cloud. And it's only as good, as the cloud is.
But there is way to improvement. The rest API works as far as I know quite good. In combination with the websocket it may get better. Or if the troubles with the websocket hold on, maybe it would be better to switch back to rest.

**Comment by Thomas55555** [comment]
The problem with rest is, that it's based on polling. So you don't get updates instantly

**Comment by denstech** [comment]
Thanks again for the updates.
How do I revert to this rest API? How does one change from this websocket dependency? Is it a different version of your integration? I have no idea what to do here, sorry. Can you advise as I'm no expert :-)

**Comment by Thomas55555** [comment]
The last version that only worked on rest API was 2021.9.0 but this version probably won't work on a current ha installation.
I'm sorry, but you have to wait until the websocket is working again. Or we (@simontegelid/I) develop something new.

**Comment by denstech** [comment]
Ok listen many thanks for your insight and help. I might try the 2021.9.0 version if it's available on your repository.
Otherwise I have seen forum discussions where users were having issues with OTHER integrations, like IKEA, Samsung etc, disconnecting. Someone proposed as a temporary solution a little HA automation which would look for the state of some entity to go 'unavailable' and then take action to RELOAD that integration. It's a very clunky fix I know..what do you think?

**Comment by denstech** [comment]
The automation works so far. It triggers on the automower activity becoming 'unknown' and does a reload of the integration so this seems to keep the connection alive. Code below if others interested in a temp fix.

`id: 'xxxxxxxxxxxxx'
alias: Shelby integration reload
description: >-
  Shelby integration is losing connection due to websocket issues. This is a
  temporary fix.
trigger:
  - platform: state
    entity_id: sensor.shelby_activity
    to: unknown
condition: []
action:
  - service: homeassistant.reload_config_entry
    data: {}
    target:
      device_id: 196d0a7f179bxxxxxxxxxxxxx
mode: single`

**Comment by Thomas55555** [comment]
The websocket started working again - three hours ago. So you probably don't need the automation anymore.

**Comment by simontegelid** [comment]
I will look into this in a few weeks when I bring out my mower from its winter sleep.

**Comment by denstech** [comment]
Thanks for update Thomas. I'll leave the automation running because I can see from the timeline/history data if and when it's triggering. That will tell us how the websocket is doing. You posted your message 23 hrs ago but my automation says it was triggered about 12 hours ago. So I'll keep you updated on what's happening if you like.

**Comment by denstech** [comment]
Hey Simon, my Shelby has been busy here (in Ireland) since February :-)

**Comment by tuupos** [comment]
> The automation works so far. It triggers on the automower activity becoming 'unknown' and does a reload of the integration so this seems to keep the connection alive. Code below if others interested in a temp fix.
> 
> `id: 'xxxxxxxxxxxxx' alias: Shelby integration reload description: >- Shelby integration is losing connection due to websocket issues. This is a temporary fix. trigger:
> 
> * platform: state
>   entity_id: sensor.shelby_activity
>   to: unknown
>   condition: []
>   action:
> * service: homeassistant.reload_config_entry
>   data: {}
>   target:
>   device_id: 196d0a7f179bxxxxxxxxxxxxx
>   mode: single`

Thanks for the automation ! I converted it for myself in node red. Works!

Seems to me the websocket is still offline. Disconnecting keeps happening.
Same issues here: [https://github.com/walthowd/ha-automower/issues/26](url)

**Comment by larserhardsen** [comment]
I am also seeing disconnects in the log, and the only way to revive the connection is to reload the integration.

This error originated from a custom integration.

```
Logger: custom_components.husqvarna_automower.entity
Source: custom_components/husqvarna_automower/entity.py:74
Integration: Husqvarna Automower (documentation, issues)
First occurred: April 11, 2022, 18:06:13 (3 occurrences)
Last logged: April 11, 2022, 18:06:13

Connection to Mariehønen Preben lost
```

HA is version 2022.4.2
