### ISSUE TITLE
Aborted - The reauthentication was successful 

### ISSUE THREAD

**Issue by Ronan-O-Keeffe** [Thomas55555/husqvarna_automower#205]
Home Assistant Core 2022.4.6
Latest automower integration 
https://github.com/Thomas55555/husqvarna_automower/releases/tag/2022.4.1

Manual install method. 

This was working before I updated today. The flow is: 
Download release, unzip, rm all in the original `husqvarna_automower` custom_components dir, copy all new files in to empty folder, chown files to HA user, stop/start HA. 
At that stage the automower integration is missing so when I add it again I get the below message. 

<img width="404" alt="Screenshot 2022-04-22 at 10 12 06" src="https://user-images.githubusercontent.com/15214886/164679201-0a50a0e6-d657-4c99-a44e-a7aa74c114e2.png">

Nothing to go on in `~/.homeassistant/home-assistant.log`

Not looking for a fix or anything, just a heads up. 

Cheers, 
R.

**Comment by Thomas55555** [comment]
thx
