### ISSUE TITLE
Persist Values when Unavailable?

### ISSUE THREAD

**Issue by jasoncross** [Thomas55555/husqvarna_automower#206]
It appears that after an error persists for a little bit the mower changes to unavailable (due to battery loss?). Would it be possible to persist the last known values?

**Comment by Thomas55555** [comment]
I don't know, what you mean exactly. Can you give me more information?

**Comment by jasoncross** [comment]
Sure. For example when the auto mower gets stuck it changes it’s status to error and has a location. But today when it eventually runs out of battery the status then changes to unavailable and it loses the location etc. it would be nice if instead the last known status and related data persisted. That’s how it worked with the other integration.

**Comment by Thomas55555** [comment]
It would be easy for coding. If we just remove this linies:

https://github.com/Thomas55555/husqvarna_automower/blob/3bd609881a85c6342c3083b07e6e20971225c6dc/custom_components/husqvarna_automower/entity.py#L58-L62

then HA wouldn't change the state to unavailable. 
But how can we find out if the mower is available or not?

**Comment by Thomas55555** [comment]
I think this can be closed now. If not, reopen it.
