### ISSUE TITLE
Status "charging" is not available

### ISSUE THREAD

**Issue by dawiinci** [Thomas55555/husqvarna_automower#210]
I don't get the status charging from the vacuum entity. It just says docked. But I need to distinguish between just docked and charging. The vacuum template support this, so I guess it can be implemented. Or am I missing something?

**Comment by Thomas55555** [comment]
I can't find in in the states. 
https://www.home-assistant.io/integrations/vacuum.template/#value_template
Only in the custom attributes. Where did you find it?

**Comment by dawiinci** [comment]
Sorry, I mixed up the states from other sources. Docked is the only option here. I guess I have to check for docked AND under 100 % then.

**Comment by Thomas55555** [comment]
You can also check the activity attribute. I think it also says charging or not

**Comment by dawiinci** [comment]
Cool, thanks for that hint.
