### ISSUE TITLE
Account passwords with non-letter or non-number characters are not working as expected

### ISSUE THREAD

**Issue by hollie** [Thomas55555/husqvarna_automower#212]
Hello,

thanks a lot for developing and sharing this extension for home assistant!

I just want to let you know that I had to change my password before I could connect to the API. My original password had some non-letter and non-number characters in it (part of it was `t(4<_h$zGrBH`) and I could not authenticate Home Assistant to my account.

After changing my password to all letters and numbers all is working as expected.

Keep up the good work!
 Lieven.

**Comment by Thomas55555** [comment]
I've tested it with the password `t(4<_h$zGrBH` and it worked for me. So I have no idea how to debug this. I close this issue. If there are further problems, let me know.

**Comment by hollie** [comment]
Hey @Thomas55555 ,

hmm weird, I was unable to get a successful coupling with the API using my original password. Either way: thank you for double-checking and thanks again for releasing this add-on for Home Assistant!

Kind regards,
 Lieven.

**Comment by Thomas55555** [comment]
I can't also explain. There was already an issue with that #25.
And the introduced stuff with `urlencode` and `quote_plus` is still in use...

**Comment by hollie** [comment]
No problem, I don't think it is a blocking issue.
