### ISSUE TITLE
Re-Authentication needed on almost every restart

### ISSUE THREAD

**Issue by MRobi1** [Thomas55555/husqvarna_automower#217]
Having an issue where I have to re-authenticate on restart. I'd estimate roughly 90% of the time re-authentication is required. After re-configuring and entering the login info, it will work again without issues. I haven't noticed it dropping a connection between restarts of the server but will watch for it a little closer.

![Capture2](https://user-images.githubusercontent.com/34860474/167145394-718a0484-9bcf-49c4-86e4-3c8d32220839.PNG)
![Capture](https://user-images.githubusercontent.com/34860474/167145427-78609e35-4535-4c37-b650-3f4f271509f0.PNG)
![Capture1](https://user-images.githubusercontent.com/34860474/167145442-c8ebc08b-bb23-4839-b9b8-b81fbd03c479.PNG)

Located in Canada so not sure which of their servers I'd be hitting. I'd assume the U.S.

**Comment by Thomas55555** [comment]
If you have more information, let me know.
It should actually only be a problem, after restarting Home Assistant. Right now, there are no triggers for re-auth while running HA.
Is your Home Assistant running all the time, or do you have longer downtimes?

**Comment by frank8the9tank** [comment]
I have the same, (due to the latest update) moved from username/pw in configuration.yaml to the oauth method as per latest update.

**Comment by frank8the9tank** [comment]
I have the same problem is the last update, see above,
Re authenticate on every reboot.
my HA is running 24/7, minus the reboots. but never down for long time.
What i can do to help solve this?

**Comment by Thomas55555** [comment]
send me an email. You can find the address here: https://github.com/Thomas55555/aioautomower/blob/main/setup.py

**Comment by frank8the9tank** [comment]
I move from a synology VM to a Home assistant VM now running on ESXI, but the strange things is now that it no longer requires to re authenticate on every reboot. so it looks for me solved, buy why???
Its not a clean install, i exported the VM to a .ova on the synology and imported it in EXSi, so pretty much the same machine.

**Comment by tuupos** [comment]
Same problem here, when I restart HA re-auth needs to be done. no problems while running HA but sometimes i need to restart because of changes or updates.
No big issue because it is not that often that i need to restart.

**Comment by tuupos** [comment]
Updating to HA .8 fixed the issue I thinks

**Comment by SanderM2** [comment]
I'm having the same problem too. Every time I restart HA I need to reauthenticate

**Comment by SanderM2** [comment]
I deleted the integration from my devices, selected to remove the authentication data too. Then added it again and it's working like before again... Weird things.
