### ISSUE TITLE
CalendarEventDevice is deprecated, modify AutomowerCalendar to extend CalendarEntity

### ISSUE THREAD

**Issue by r3dsouza** [Thomas55555/husqvarna_automower#218]
Thanks for creating and maintaining this custom component. 

After upgrading my HA to the lastest version, I recently noticed that I get the following warning in the logs:
`WARNING (MainThread) [homeassistant.components.calendar] CalendarEventDevice is deprecated, modify AutomowerCalendar to extend CalendarEntity`

Just wanted to check if there is something needed to be updated to ensure that this component does not break in future releases.

**Comment by Thomas55555** [comment]
working on it in #215
