### ISSUE TITLE
Add problem sensor and/or error messages

### ISSUE THREAD

**Issue by Gloomyeye** [Thomas55555/husqvarna_automower#224]
Hallo,

it is possible to add a problem sensor and/or a message sensor with the error message content if some messages are available?

I could use the status of the mower for a error detection, but maybe a dedicated problem sensor would be more convenient.

**Comment by Gloomyeye** [comment]
Hello @Thomas55555 ,
thanks for adding a sensor in the last version. However, I thought that the problem sensor is a binary_sensor with device class "problem". In addition, the binary_sensor could have a attribute like "content" or "failure" with shows the error message content like in the husqvarna app. The entity id of the sensor could be binary_sensor.<mower>_failure.

Examples of what I thought are the overvoltage sensors of a shelly device or the failure sensor of the custom miele integration:
<img width="799" alt="problem_sensors_01" src="https://user-images.githubusercontent.com/69754128/168729469-d00d4cb9-86b3-4413-9dbb-499b00d9da8a.png">

<img width="350" alt="problem_sensors_02" src="https://user-images.githubusercontent.com/69754128/168729539-a5a856c6-b220-4950-b8ca-785cd275717a.png">

The current problem sensor implementation with the state "WEEK_SCHEDULE" shows me the current configured behaviour. So, I would see here:
- "WEEK_SCHEDULE" -> Normal week scheduling active
- "MANUALLY_SCHEDULE" -> Start the mower outside the scheduling for example with the service husqvarna_automower.park_and_start
- "NO_SCHEDULE" -> No scheduling defined so far

<img width="384" alt="problem_sensors_03" src="https://user-images.githubusercontent.com/69754128/168730222-c2b98c06-9371-4d57-808e-f158ff214e41.png">

What do you think?

**Comment by Thomas55555** [comment]
No, thats not right.
Possible values for this sensor are:
`[WEEK_SCHEDULE, PARK_OVERRIDE, SENSOR, DAILY_LIMIT, FOTA, FROST]`
These are the restricted reasons from Husqvarna, why the mower can't mow.
Also possible are all the error messages, that can be found here: https://developer.husqvarnagroup.cloud/apis/Automower+Connect+API#/status%20description%20and%20error%20codes
If there is no "problem", then the sensor returns `None`

**Comment by Gloomyeye** [comment]
Ah okay, thank you for the information. I created the following template sensor for me:
- binary_sensor:
    - name: "Husky Failure"
      unique_id: gar_mower_husky_failure
      state: "{{ not ( is_state('sensor.gar_mower_husky_problem', 'unknown') or is_state('sensor.gar_mower_husky_problem', 'WEEK_SCHEDULE') ) }}"
      device_class: problem

It is possible to get the error codes as well as the corresponding texts (see [https://developer.husqvarnagroup.cloud/apis/Automower+Connect+API#/status%20description%20and%20error%20codes](here))? So, if the state of the mower has "ERROR, FATAL_ERROR, ERROR_AT_POWER_UP - An error has occurred. Check errorCode. Mower requires manual action." then it would be great if we can get the error code (+ text) in Home Assistant.
