### ISSUE TITLE
New installation wont connect

### ISSUE THREAD

**Issue by danjul89** [Thomas55555/husqvarna_automower#231]
Hello,

Trying to connect but i can't get it to work.

--- "Full logs" ---
`2022-05-16 19:46:54 WARNING (MainThread) [custom_components.husqvarna_automower.config_flow] Automower Connect API not connected
2022-05-16 19:46:54 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 2c2730fd-aa37-429c-ac56-fa948aab4bef for husqvarna_automower
  File "/config/custom_components/husqvarna_automower/__init__.py", line 95, in async_setup_entry
  File "/config/custom_components/husqvarna_automower/__init__.py", line 109, in async_setup_entry`

--- HASS --- 
Home Assistant Core 2022.5.4
Home Assistant Supervisor 2022.05.2
Home Assistant OS 8.0
Kernel version 5.15.38
Agent version 1.2.1

**Comment by Thomas55555** [comment]
Isn't there an issue template with checkboxes to fill out?
Because that indicates:
`Automower Connect API not connected`, that the Automower Connect API is not connected.
Have you connected this on the Husqvarna site, like this?
![DeepinBildschirmfoto_Bereich auswählen_20220516200748](https://user-images.githubusercontent.com/59625598/168655677-22c9a002-63a1-4123-be8b-87f2c1b74103.png)

**Comment by danjul89** [comment]
Hah! Missed that one, it was hidden behind the cookie accept popup :'D

Thanks for the fast reply!

![image](https://user-images.githubusercontent.com/30293623/168658767-b20380d9-9389-4b3c-bb13-6ac1c5410663.png)

**Comment by danjul89** [comment]
Hm, I don’t know what you mean by issue template :-/

**Comment by chammp** [comment]
He means this pre-filled issue text with checkboxes to make the reporter check the most basic pre-requisites:

![grafik](https://user-images.githubusercontent.com/57918757/168825198-671b7246-2aa8-4ebb-bb66-84da69bc8567.png)

I can report this as working I guess :)

**Comment by danjul89** [comment]
> He means this pre-filled issue text with checkboxes to make the reporter check the most basic pre-requisites:
> 
> 
> 
> ![grafik](https://user-images.githubusercontent.com/57918757/168825198-671b7246-2aa8-4ebb-bb66-84da69bc8567.png)
> 
> 
> 
> I can report this as working I guess :)

No, i didn't get any template unfortunately
