### ISSUE TITLE
Invalid client: `redirect_uri` does not match client value

### ISSUE THREAD

**Issue by kindyyyy** [Thomas55555/husqvarna_automower#245]
Hello,

Each time, I get the following message: "Invalid client: `redirect_uri` does not match client value"

<img width="402" alt="image" src="https://user-images.githubusercontent.com/107203454/173153249-c0231453-0a1d-43d8-b7ed-a0dde5ca6f43.png">

<img width="441" alt="image" src="https://user-images.githubusercontent.com/107203454/173153280-54e15ef7-1ed8-488b-88d2-6417cd8514fe.png">

<img width="440" alt="image" src="https://user-images.githubusercontent.com/107203454/173153347-acd46569-5bfe-444e-983a-c65c1cb62f83.png">

<img width="590" alt="image" src="https://user-images.githubusercontent.com/107203454/173153186-a91c9ff8-41c6-44ba-9834-865910e18c34.png">

Have you ever encountered this problem?

**Comment by prairiesnpr** [comment]
I just got bit by this.  If the "my" integration is enabled, part of the defual config, in home assistant it hijacks the oauth urls.  You either need to disable the integration or add that url to the authorized callback urls on the Husqvarna developer site.

**Comment by kindyyyy** [comment]
Sorry, but I have 2 questions. Where can I disable this "my" integration? And what does this auth url look like?

**Comment by prairiesnpr** [comment]
If you've configured https://my.home-assistant.io/redirect/oauth as the redirect link for your app in the Husqvarna developer portal and you still get that error, then it's probably something else.  Look at the URL when it opens the Husqvarna site to authenticate, you can see the redirect URL that's passed to Husqvarna there, it should match https://my.home-assistant.io/redirect/oauth or whatever url you set for your app.

**Comment by kindyyyy** [comment]
I misspoke. Indeed with this url "https://my.home-assistant.io/redirect/oauth", I can register the plugin.

Thank you

**Comment by Lancelot852** [comment]
Hi,
do you add 2 urls or only one ?
Could you give me an example ?
when i m here
image
image
505×713 66.1 KB

what do i have to choose ? Redirect to ?

**Comment by Lancelot852** [comment]
Hi, I solve :)
