### ISSUE TITLE
Not possible to add integration

### ISSUE THREAD

**Issue by Wiftavarf** [Thomas55555/husqvarna_automower#263]
Setting API-key all 36-digit
Enter username and password.

Just gets an error stating to enter API-key, user name and password.
Just did that.

Integration won't add.

**Comment by Thomas55555** [comment]
Can you please support with more information. There is an issue template you can fill out, with al the basic input.

**Comment by Wiftavarf** [comment]
When I try to add integration ”Husqvarna Automover”.
I can select two ways to Log in.

Select option 1: Log in with Authorization Code 
I get this error:
![D1A577CD-73D6-4493-8125-0AA343E09EFB](https://user-images.githubusercontent.com/52937779/176536554-f442f567-2c8d-4bcf-9f27-7344d2f487e5.png)

Trying option 2: Log in with API-key I get this error:
![D9BA739B-363B-43D1-A191-52C3DC4309B4](https://user-images.githubusercontent.com/52937779/176536664-4ad61b65-2407-41c9-b87f-ef2b2d869e6d.png)

Integration not adding!
Can’t get past these errors.

All other steps are added and checked.

**Comment by sarahmva** [comment]
I am facing the same problem. 
I have created the application, added the Authentication AP and the Automower Connect API, tested the app using the curl example.

I have also added the secret and the appkey to the config

if I try:
![image](https://user-images.githubusercontent.com/68161487/176727058-250a6cce-0bce-4ab3-815c-41e06ed04212.png)

HA cannot validate the config: **Error loading /config/configuration.yaml: Secret fc82[...]**

![image](https://user-images.githubusercontent.com/68161487/176727495-0c4e0c4e-b7b1-46bc-999d-5f8ded1e1937.png)

I enabled debug logging but there are no entries in the log.

**Comment by Wiftavarf** [comment]
I actually got this to work, by add via option 1.

What I did was when you return to HA wia return link, there is an error.

But by leaving that page open and retry, in an other window, the session was ”open” to complete the integration addon.

**Comment by sarahmva** [comment]
Ah, I think I know what is happening....
1. It is important to enter **https://my.home-assistant.io/redirect/oauth** as redirect URL in the application on the Husqvarna website
2. When configuring for the first time, the redirect URL is escaped, this seems to cause issues: **https%3A%2F%2Fmy.home-assistant.io%2Fredirect%2Foauth**. When opening via the button in teh config flow, the URL is not escaped and then it does work...

A little strange, I am glad it now worked. Thanks @Wiftavarf for the tip!

**Comment by hypyke** [comment]
So I am confused.  I've tried to follow the directions and the tips here but it's still not clear.  I get an error if I try either way.  Using the key username and pass or doing the web auth.  I have the configuration.yaml entry and it's correct. So what is the correct way to make this work
![2022-07-02 21_38_18-My Home Assistant — Mozilla Firefox](https://user-images.githubusercontent.com/3076893/177021118-b4314671-7e4a-4be6-825e-07195c53c9e2.png)
![2022-07-02 21_38_29-Husqvarna Developer Portal — Mozilla Firefox](https://user-images.githubusercontent.com/3076893/177021119-2c94450a-60cd-41e6-8d2b-51eb4ef232a4.png)
![2022-07-02 21_39_34-Settings – Home Assistant — Mozilla Firefox](https://user-images.githubusercontent.com/3076893/177021120-0098c349-0bd1-4516-b208-4fef61653526.png)
?

**Comment by ardzeus** [comment]
I also face same "Invalid client: `redirect_uri` does not match client value" problem. I've tried many formats of Redirect URI by escaping and not escaping, using my.home-assistant.io and direct instance URL of my setup, but I always just get that redirect_uri error message.

**Comment by xavierdemoor** [comment]
I have the exact same problems.

The URL of my home assistant (https://.../redirect/oauth) gives me an error saying invalid parameters given when I try to visit it.

When I try this via the apikey/apisecret, I got the same error "invalid client : redirect Uri".

When I try via apikey login/password I got an error saying to check if those info are valid.

Can't figure it out.

**Comment by xavierdemoor** [comment]
After trying several methods, I finally understand what @sarahmva said. I pressed the "Open" button instead of following the auto-opened window. BUT, now the integration just say "Error" and I can't finalize.

I tried to set myhomeassistant to local url and Nabu casa external url. Nothing works.

**Comment by BFipsen** [comment]
I cant find config.storage\application_credentials, can anyone please help me how to find this?

**Comment by trickiegt** [comment]
\config\.storage  -- sorry it was missing a \   --- however... depends on how you access your server, there's alot of methods... i used samba share addon and then connected via the IP address in a windows explorer window \\192.168.10.11\config\.storage

**Comment by BFipsen** [comment]
thankyou, i forgot to show hidden files in windows.

I deleted the file at got the posibility to insert the credentials again, but i still godt the: Invalid client: `redirect_uri` does not match client value

any idea why?

**Comment by trickiegt** [comment]
I made the mistake of changing `https://my.home-assistant.io/redirect/oauth`  to my personal instance... `https://myhomeassist.duckdns.org/redirect/oauth`   -- if you did that, I would recommend changing it to what `https://my.home-assistant.io/redirect/oauth`

As an extra step, you might want to goto [](https://my.home-assistant.io/) first and make sure it is pointing to your home assistant site

**Comment by anatolyk82** [comment]
I have the same problem, got always `Invalid client: redirect_uri does not match client value`

**Comment by mulcmu** [comment]
I encountered that error when had an extra space at the end to the url.  Extra space was selected during the cut and paste.  Everything looked correct but that was enough to fail the authorization process.

**Comment by BFipsen** [comment]
I can't se why, but as trickiest says, try to set: https://my.home-assistant.io/redirect/oauth
It worked for me.

**Comment by anatolyk82** [comment]
It's working now. I missed "My Home Assistant" integration actually. It would be great to mention it in the documentation here to avoid such misunderstandings in future. Thank you!

**Comment by mulcmu** [comment]
PR #304 adds this:

> The My Home Assistant redirect feature needs to be setup to redirect to your home assistant installation. See https://my.home-assistant.io/faq/ for additional information.

Preview here:
https://github.com/mulcmu/husqvarna_automower/tree/readme-overhaul

**Comment by notacoderjustauser** [comment]
> `\config\.storage` -- sorry it was missing a \ (apparently its automatically removed) --- however... depends on how you access your server, there's alot of methods... i used samba share addon and then connected via the IP address in a windows explorer window `\\192.168.10.11\config\.storage`

Thsi was the solution for my issue
