### ISSUE TITLE
I get "undefined" error while confiuring integration 

### ISSUE THREAD

**Issue by mcfly76** [Thomas55555/husqvarna_automower#265]
**Prerequirements**
[X ] I have connected my mower(s) to the Automower Connect App
[X ] I have connected my Husqvanra developers account to the Authentication API
[X ] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
I get an error message "Not possible to load the configuration flow: undefined" when I try to add the integration in the Devices and Services screen in HA.

**Expected behavior**
To complete the configuration steps.

**Screenshots**
<img width="439" alt="Schermata 2022-06-27 alle 10 58 05" src="https://user-images.githubusercontent.com/6482973/175901198-a8c1b624-0bc8-4464-8054-5947e1a711e8.png">

**Additional context**
HA version:  core-2022.5.3
Husqvarna Automower integration version: 2022.6.2
I tried both from local HA url and from external Nabu Casa url.

**Comment by prairiesnpr** [comment]
Logs?

**Comment by mcfly76** [comment]
After upgrading to the latest HA version (2022.6.7) the integration works fine.
Thanks
