### ISSUE TITLE
HA says "The component is not configured"

### ISSUE THREAD

**Issue by tangix** [Thomas55555/husqvarna_automower#283]
**Prerequirements**
[X] I have connected my mower(s) to the Automower Connect App
[X] I have connected my Husqvanra developers account to the Authentication API
[X] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
I had the Automover integration running up until today when I upgraded from 2022.7.2 to 2022.7.3 and restarted HA. After that the integration showed that it need to be reconfigured. Clicking the red "Reconfigure" button gave me the message indicated in the screenshot below. 
After several reboots and attempts to reconfigure I completely removed the integration rebooted, recreated the API integration at husqvarna and tried adding it again in HA. Still the same issue, message is shown directly.

I have looked through configuration.yaml but found no references to automower.

Is there a way to make HA completely forget the configuration of the integration? Where should I look?

**Expected behavior**
Be able to follow the instructions from the docs.

**Screenshots**
When trying to add I get the following message and nothing more:
<img width="579" alt="image" src="https://user-images.githubusercontent.com/1013635/178212958-7b1904c6-4901-4119-aad0-94b946c4d4b3.png">

![2022-07-11_09-44-47](https://user-images.githubusercontent.com/1013635/178214197-cc112bdf-509f-412e-ad4c-a970094164cf.gif)

**Additional context**
HA 2022.7.3 running on HAOS 8.2
Trying with `debug` setting for logs but can only find this:
```
2022-07-11 09:48:22 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration husqvarna_automower which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

**Comment by Thomas55555** [comment]
Sorry, I've changed the documentation already, because I'm planning to enter this UI. But here is the old documentation:
https://github.com/Thomas55555/husqvarna_automower/tree/2022.7.0#home-assistant
You have to add `client_id` and `client_secret` in your `configuration.yaml`

**Comment by tangix** [comment]
Thanks! 
Do you have any hints as what to put in the now required redirect field on the Husqvarna site?
<img width="612" alt="image" src="https://user-images.githubusercontent.com/1013635/178218738-6e6b089c-c74e-46a7-ae9d-a415b70b1300.png">
I have tried my local non-http address and my habu casa but failed.

**Comment by Thomas55555** [comment]
Yes, it's also in the link above. You have to enter this: https://my.home-assistant.io/redirect/oauth

**Comment by tangix** [comment]
OK - worked the second time! All good now, just need to reconfigure my automations.
Thank you!
