### ISSUE TITLE
Log warning regarding username

### ISSUE THREAD

**Issue by johanschelin** [Thomas55555/husqvarna_automower#305]
I still get log warnings that the integration uses username and password after change to API via Oauth service. 

 Nothing left in configuration.yaml 

Removed Integration and Hacs - restart and re-add. Still gets same warning. 

Logger: custom_components.husqvarna_automower
Source: custom_components/husqvarna_automower/__init__.py:91 
Integration: Husqvarna Automower ([documentation](https://github.com/Thomas55555/husqvarna_automower), [issues](https://github.com/Thomas55555/husqvarna_automower/issues)) 
First occurred: 12:00:37 (1 occurrences) 
Last logged: 12:00:37

Log-in with password/username is depracated. Please set-up client_id and client_secret in the Application Credentials form

**Comment by Thomas55555** [comment]
Will be changed in the next release

**Comment by johanschelin** [comment]
Fixed in the latest version! Thnx
