### ISSUE TITLE
How to authenticate?

### ISSUE THREAD

**Issue by MRobi1** [Thomas55555/husqvarna_automower#314]
I've just updated to the latest version and have absolutely no clue how to authenticate. I was previously using username/password.

The integration loads and "Requires Configuration".

The instructions state:
Create an account on [Husqvarna developers portal](https://developer.husqvarnagroup.cloud/applications). Connect The Authentication API and Automower Connect API. As redirect-URI set https://my.home-assistant.io/redirect/oauth. If you haven't set up My HomeAssistant already. Enter this URL for your instance http://192.XX.XX.XXX:8123/

It asks for:
Name:
OAuth Client ID:
OAuth Secret: 

For Name I put the name of the application created in Husqvarna.
OAuth Client ID: I tried Application Key
OAuth Secret: I tried Application Secret

It just returns "Cannot authenticate."

A comment 6 days ago states "You have to add client_id and client_secret in your configuration.yaml". Are client_id and client_secret the application key and application secret? What should they be added as and how?

**Comment by DotNet2Web** [comment]
@MRobi1, I got the same issue.

What I just did was:

- Delete the existing integration
- Delete the existing oauth token (https://github.com/Thomas55555/husqvarna_automower#remove-credentials) 
- Reboot HA
- Installed the integration
- Re-entered the following (created at the developers page of husqvarna)
-  Name
-  ApplicationKey
-  ApplicationSecret

And it works again.

**Comment by Thomas55555** [comment]
Can you enable debugging, like described in the readme and report the logs?
