### ISSUE TITLE
Bluetooth Support

### ISSUE THREAD

**Issue by TomF79** [Thomas55555/husqvarna_automower#330]
Today is a HA Update 8.2022 available with Bluetooth Support Integration.

https://www.home-assistant.io/blog/2022/08/03/release-20228/

Maybe now it is possible to use Automower with Bluetooth?

BR Tom

**Comment by Thomas55555** [comment]
Pretty sure. But someone has to program it. And I can't, because I don't have one of these mowers. But if you like to do it, you can do it?

**Comment by TomF79** [comment]
I have the Automower 305 (2020) but i have no idea about coding 😅

**Comment by Thomas55555** [comment]
:rofl:

**Comment by GitWally** [comment]
I have the same requirement, because I would like to buy Automower 305.
But garden is still a battle field ... 
Hope somebody will do that!

**Comment by AlessandroTischer** [comment]
> Pretty sure. But someone has to program it. And I can't, because I don't have one of these mowers. But if you like to do it, you can do it?

I have a 315 and some (little) coding knowledge. Unfortunately I don't know where to start. Would you like to cooperate in order to extend this integration to all the Bluetooth only capable mowers?

**Comment by Thomas55555** [comment]
I expected you can do something like bluetooth sniffing: https://bleak.readthedocs.io/en/latest/scanning.html
But this seems to work only for BLE. So sorry, maybe it's not possible anyway.
I also don't have any knowledge in bluetooth.

**Comment by alistair23** [comment]
I have started to reverse engineer the Bluetooth commands. You can find what I have so far here: https://github.com/alistair23/AutoMower-BLE

I currently have Python scripts that can communicate with the mower to get information and send commands. I can query basic information, including state. I can also pause, resume and override the mowing from Python.

The next step is to work on a HA integration. If anyone wants to help you can test what I currently have, help with a HA integration or sponsor the work

**Comment by Thomas55555** [comment]
Wow, that's cool. I'd like to add this to my integration, but my mower doesn't support Bluetooth. But if you'd like to contribute to the existing integration, or the WIP official HA integration it would be nice.

**Comment by alistair23** [comment]
Ah cool!

I was planning on writing my own integration. I thought it would be difficult to combine this with your, as they are both pretty independent.

If you think it would make sense to add it to the WIP official HA integration I can look at that. If you can provide a pointer of where/how it could work I can go from there. The settings will need to be split apart to support the two use cases
