### ISSUE TITLE
Accidently deleted Automower camera integration

### ISSUE THREAD

**Issue by christiankropf** [Thomas55555/husqvarna_automower#332]
I accidently delted the Automower camera integration. Now i am not able to restore it. I tried to add and remove the Integration but only the husqvarna_automower integration appears after a complete new installation. Any ideas what i could do?

The rest works like a charm :)

**Comment by prairiesnpr** [comment]
This is certainly odd, if the integration was removed it the camera entity should've been recreated.  Were there any errors in the logs when you re added the integration?  It's not listed under disabled entities and the camera is enabled in the config?
