### ISSUE TITLE
Getting access to statistics

### ISSUE THREAD

**Issue by paulbusse** [Thomas55555/husqvarna_automower#333]
**Prerequirements**
[ X] I have connected my mower(s) to the Automower Connect App
[X ] I have connected my Husqvanra developers account to the Authentication API
[ X] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
Not a bug, but a feature request :-).
I would like to get access to the statistics that come with `GET /mowers/{id}`

**Expected behavior**
I'm very lazy in e.g. changing the blades, so I would like to set alarms on the time they were used. If I could get access to these statistics from within HA, I could send notifications there.

```json
{
  "data": {
    "type": "mower",
    "id": "256b2365-33a7-46fe-a9fb-e67e84f4ac01",
    "attributes": {
      "battery": {...},
      "mower": {...},
      "calendar": {...},
      "planner": {...},
      "metadata": {...},
      "positions": [...],
      "settings": {...},
      "statistics": {
        "cuttingBladeUsageTime": 16526,
        "numberOfChargingCycles": 31,
        "numberOfCollisions": 14641,
        "totalChargingTime": 8412,
        "totalCuttingTime": 120505,
        "totalRunningTime": 181939,
        "totalSearchingTime": 32305
      }
    }
  }
}
```

**Screenshots**

**Additional context**

**Comment by Thomas55555** [comment]
This is already implemented. But the entity is not enabled by default. You have just to enable it.

**Comment by paulbusse** [comment]
Oops. Sorry, missed that. I wrote this before my upgrade... Thanks for the implementation.
