### ISSUE TITLE
Map image file erased after every upgrade

### ISSUE THREAD

**Issue by robertoash** [Thomas55555/husqvarna_automower#341]
**Prerequirements**
[X] I have connected my mower(s) to the Automower Connect App
[X] I have connected my Husqvanra developers account to the Authentication API
[X] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
Every time I upgrade the add-on via HACS, after restarting, I get the "Configure map image" on my camera card. I am guessing `/config/custom_components/husqvarna_automower/resources/map_image.png` is overwritten to a blank file on every upgrade. 

**Expected behavior**
Upgrading should leave user files intact if they exist. User files under "resources" should only be restored if they have been completely deleted. 

**Screenshots**
![image](https://user-images.githubusercontent.com/42000824/185740640-425f3b50-a1a7-4cb7-b10d-50b4700fc7ba.jpeg)

**Comment by prairiesnpr** [comment]
map_image.png is just a fall back resource to use if another image isn't configured.  You can set a custom path in the configuration that points to your custom image. I use the www folder inside my config directory,  but it can be anywhere that the home assistant user has permission to access.

**Comment by robertoash** [comment]
You are completely right. 

I repointed the configuration to a custom path outside of `/config/custom_components/husqvarna_automower/` (I also put it under `/config/www/`) and now the image is not updated when updating the add-on.

Thanks so much for the help!
