### ISSUE TITLE
RE-installed HA but can't re-install Husqvarna Automower

### ISSUE THREAD

**Issue by nolenjohan** [Thomas55555/husqvarna_automower#350]
**Prerequirements**
[ ] I have connected my mower(s) to the Automower Connect App
[ ] I have connected my Husqvanra developers account to the Authentication API
[ ] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
When trying to add the integration ((after installing it through HACS) I constantly receive this web page:
![image](https://user-images.githubusercontent.com/34334118/189736930-1abb55b4-7e71-4209-8c23-63337893c89d.png)

**Expected behavior**
An opportunity to connect to my Husqvarna Application.

**Screenshots**
![image](https://user-images.githubusercontent.com/34334118/189737049-539b2664-8d52-431b-9007-c7f120033370.png)

**Additional context**
It was working fine before the re-installation of HA, I even created a new Husqvarna Application but without success.

**Comment by Thomas55555** [comment]
Have you had an look at #263 this looks quite similar?

**Comment by nolenjohan** [comment]
I solved it by removing existing credentials for this integration in HA, after the new installation I added a backup which had the credentials included.
