### ISSUE TITLE
no mower gets added after "sucessful installation"

### ISSUE THREAD

**Issue by aeqvist** [Thomas55555/husqvarna_automower#352]
I've installed the integration with HACS and configured as it should, everything seems fine. But HA doesn't seem to get the Mower from API (get /mower). 

Only thing i can find in debuglog is "2022-09-27 22:44:27.016 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration husqvarna_automower which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant" But that isn't a issue :)
Any manual steps i forgot to add to configuration.yaml or?

HA versions: Home Assistant 2022.9.7
                     Supervisor 2022.09.1
                     Frontend-version: 20220907.2 - latest

**Comment by Thomas55555** [comment]
Did you do that?
**Prerequirements**
[ ] I have connected my mower(s) to the Automower Connect App
[ ] I have connected my Husqvanra developers account to the Authentication API
[ ] I have connected my Husqvarna developers account to the Automower Connect API

**Comment by aeqvist** [comment]
I've connected to Automower app but i think after throubleshooting a bit that my mower isn't connected to the cloud.
It's a new mower and got problem with getting the code for pairing at the mower display. So i guess that my app is just connected with bluetooth to the mower... 

So hopefully there's just a local problem in my mower.
