### ISSUE TITLE
Integration cannot authenticate after installing

### ISSUE THREAD

**Issue by AOskam** [Thomas55555/husqvarna_automower#366]
**Prerequirements**
[ X] I have connected my mower(s) to the Automower Connect App
[ X] I have connected my Husqvanra developers account to the Authentication API
[X ] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
After following all steps as explained, the integration loads into HA, but says it cannot authenticate and requires re-authentication.
Instellen mislukt: could not authenticate

Log file:
2022-11-09 21:51:06.425 ERROR (MainThread) [aioautomower.rest] Response mower data: <ClientResponse(https://api.amc.husqvarna.dev/v1/mowers/) [429 ]>
<CIMultiDictProxy('Content-Type': 'application/json', 'Content-Length': '28', 'Connection': 'keep-alive', 'Date': 'Wed, 09 Nov 2022 20:51:06 GMT', 'x-amzn-RequestId': '1f0e50da-c89d-46de-acc4-e26adb5217da', 'x-amzn-ErrorType': 'LimitExceededException', 'x-amz-apigw-id': 'bWfdHHTtjoEF0pg=', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 e345c29560592087623dbe75e8d765d6.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'AMS1-P2', 'X-Amz-Cf-Id': 'QjaWJYIxNaSJ-tntSe5JPVZ2SaXOWTCIO9kejoOetdy55lF9WIoWUQ==')>
2022-11-09 21:51:06.451 WARNING (MainThread) [homeassistant.config_entries] Config entry 'husqvarna_automower' for husqvarna_automower integration could not authenticate

**Expected behavior**
authentication 

**Additional context**
HA 2022.10
Synology docker, so container version
dual IP adresses on home assistant due to dual connection on the synology.

**Comment by Thomas55555** [comment]
429 is limit exceeded. Can you try it again. If it doesn't work, create a new API key and try it again

**Comment by Thomas55555** [comment]
With the old key?
As far as I know, 429 should only happen, if at least on of these conditions is exceeded:
- Max 1 request per second and appKey.
- Max 10 000 request per month and appKey.

If you haven't used your key before, then you did enough to prevent this error.

**Comment by RodEzIO** [comment]
same problem here, key never used outside your integration.

`This error originated from a custom integration.

Logger: aioautomower.rest
Source: custom_components/husqvarna_automower/__init__.py:40
Integration: Husqvarna Automower (documentation, issues)
First occurred: 1:00:43 AM (4 occurrences)
Last logged: 9:37:03 AM

Response mower data: <ClientResponse(https://api.amc.husqvarna.dev/v1/mowers/) [429 ]> <CIMultiDictProxy('Content-Type': 'application/json', 'Content-Length': '28', 'Connection': 'keep-alive', 'Date': 'Sun, 20 Nov 2022 00:00:43 GMT', 'x-amzn-RequestId': 'cf842938-2d7d-4871-8fb5-a35e1a17262b', 'x-amzn-ErrorType': 'LimitExceededException', 'x-amz-apigw-id': 'b34m1F2ljoEFXaw=', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 483fdb1ba41b89c2c2bdf32814003bc0.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'MXP63-P3', 'X-Amz-Cf-Id': 'rywncWUM3WQdXu5y78jjJUKNpd6-DQ9pnri8v93dGwihXHy8XdOVJg==')>
Response mower data: <ClientResponse(https://api.amc.husqvarna.dev/v1/mowers/) [429 ]> <CIMultiDictProxy('Content-Type': 'application/json', 'Content-Length': '28', 'Connection': 'keep-alive', 'Date': 'Sun, 20 Nov 2022 08:35:13 GMT', 'x-amzn-RequestId': 'd6610e02-2b2b-46b3-bdef-7dd1edae6d00', 'x-amzn-ErrorType': 'LimitExceededException', 'x-amz-apigw-id': 'b5D-SFpUDoEF6Vg=', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 7a06a73d3c4d9b2940678fa230525000.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'MXP64-C1', 'X-Amz-Cf-Id': 'w9hdyPVkR8S5PYj3O__248qeA_eAHziXJE2u-rog4wom1RhHR6CUJw==')>
Response mower data: <ClientResponse(https://api.amc.husqvarna.dev/v1/mowers/) [429 ]> <CIMultiDictProxy('Content-Type': 'application/json', 'Content-Length': '28', 'Connection': 'keep-alive', 'Date': 'Sun, 20 Nov 2022 08:35:41 GMT', 'x-amzn-RequestId': '74b4f5e5-203f-49b6-b126-821e10c0df99', 'x-amzn-ErrorType': 'LimitExceededException', 'x-amz-apigw-id': 'b5ECnGsfjoEFYRw=', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 0f6f1904b6904f4881311d3f5570a9aa.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'MXP64-C1', 'X-Amz-Cf-Id': 'WsFRVzYlcKppayd69lnjNjCgeQcok3JIOq9K4g2uSZqPW_NblHbIDg==')>
Response mower data: <ClientResponse(https://api.amc.husqvarna.dev/v1/mowers/) [429 ]> <CIMultiDictProxy('Content-Type': 'application/json', 'Content-Length': '28', 'Connection': 'keep-alive', 'Date': 'Sun, 20 Nov 2022 08:37:03 GMT', 'x-amzn-RequestId': '17dfe812-eba3-4e9a-9861-65961cebf331', 'x-amzn-ErrorType': 'LimitExceededException', 'x-amz-apigw-id': 'b5EPbGC9joEFs8Q=', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 15e6afc335dbbf726da2dd95038f862a.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'MXP64-P1', 'X-Amz-Cf-Id': 'miK4z31yxIp2MI-nlmL77WlHnKpfaBxOWNJthxjiiMnsLYU-KP6I4A==')>`

**Comment by Thomas55555** [comment]
I've tried it several times with a new key, but I can't reproduce the error. I've no idea, what the reason could be.

**Comment by docBliny** [comment]
Just chiming in. I had the same thing happen (rate limit exceeded). The first time I noticed it was after I had to perform several HA restarts when reloading configuration. I had to delete the existing application and create a new one. Just changing the API credentials didn't work.

**Comment by Herbs851** [comment]
Hi all,

Same thing here.
It seems to happen only when I send orders from HA.
The sensor update seems to work fine.

**Comment by Thomas55555** [comment]
> Hi all,
> 
> Same thing here. It seems to happen only when I send orders from HA. The sensor update seems to work fine.

Yes, this is because the sensor update works with the websocket, which has no limit.

I have two API-Keys. With one  I also got this error three days ago, with the other not. Today both work again. I can't explain why.
