### ISSUE TITLE
Reenable cutting height for 320

### ISSUE THREAD

**Issue by m7r** [Thomas55555/husqvarna_automower#367]
**Prerequirements**
[x] I have connected my mower(s) to the Automower Connect App
[x] I have connected my Husqvanra developers account to the Authentication API
[x] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
cutting height entity not visible for my 320 updated to 420 Firmware (same hardware just a rebrand)

**Expected behavior**
Entity is visible

**Screenshots**

**Additional context*
Since commit a9748f there is a whitelist for supported models.
I have added the 320 to the list and can confirm that it will work.

**Comment by Thomas55555** [comment]
Can you make a pull request?
