### ISSUE TITLE
warning after upgrade HA to 2023.2

### ISSUE THREAD

**Issue by eddysteurs** [Thomas55555/husqvarna_automower#380]
following warning appears after HA upgrade to 2023.2 

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 10:18:39 (1 occurrences)
Last logged: 10:18:39

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for husqvarna_automower using this method at custom_components/husqvarna_automower/__init__.py, line 47: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by Thomas55555** [comment]
#378
