### ISSUE TITLE
Map Camera says 'Cleaning' instead of 'Mowing'

### ISSUE THREAD

**Issue by wiljums** [Thomas55555/husqvarna_automower#392]
When the Map Camera is enabled, it shows the status as 'Cleaning' instead of 'Mowing'

**Comment by NickWhitNTES** [comment]
Same issue, came here to report.  Please change this, or give us a way to make the change

**Comment by jjmerri** [comment]
My Map Camera is disabled and it still says cleaning instead of mowing.

**Comment by robinostlund** [comment]
I think this is a limitation of home assistant vacuum sensor as home assistant doesn't currently have any law mowing sensor.

**Comment by Thomas55555** [comment]
The status is somethin different than the state. See #91

**Comment by Thomas55555** [comment]
You can try version 2023.6.0b0 of this integration. Please report, if it's working

**Comment by jjmerri** [comment]
@Thomas55555 mine says "mowing" now on version 2023.6.0b1. thank you!
