### ISSUE TITLE
Websocket Connection is not working anymore

### ISSUE THREAD

**Issue by ebnerjoh** [Thomas55555/husqvarna_automower#422]
**Prerequirements**
[X] I have connected my mower(s) to the Automower Connect App
[X] I have connected my Husqvanra developers account to the Authentication API
[X] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
Websocket Connection fails after a couple of minutes after restarting HA.

```
2023-04-13 12:37:37.507 DEBUG (MainThread) [aioautomower.session] Age in sec: 1236
2023-04-13 12:37:37.509 DEBUG (MainThread) [aioautomower.session] Age in sec: 860
2023-04-13 12:37:37.509 DEBUG (MainThread) [aioautomower.session] No ws updates anymore and mower connected, ws probably down or mower shortly before disconnecting
2023-04-13 12:40:10.516 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [23427020043696] Connection closed by client
```

The Integtration doesnt get any updates from the Automower anymore. Push is still working.

Diagnostics Infos:

` "data": { "config_entry": { "entry_id": "...", "version": 2, "domain": "husqvarna_automower", "title": "husqvarna_automower", "data": { "auth_implementation": "husqvarna_automower", "token": { "access_token": "**REDACTED**", "scope": "sg-integration-api:read iam:read sg-integration-api:write amc:api", "expires_in": 86399, "refresh_token": "**REDACTED**", "provider": "husqvarna", "user_id": "...", "token_type": "Bearer", "expires_at": 1681528663.9692311, "status": 200 } },`

**Comment by Thomas55555** [comment]
Regarding to the logs the websocket connection was probably down. It started for me to work again on 2023-04-15 00:50:17.778.
Can you check, if you still have this issue? I don't think it's a problem of the integration

**Comment by ebnerjoh** [comment]
Yes, you are right. 

I checked now and websocket is stable again. I think the confusion was because it happened just right after the integrations upgrade.

So no issue of the integration but seems to be an issue at Husky side.
