### ISSUE TITLE
Integration entities not updating without a reload

### ISSUE THREAD

**Issue by Mithrox** [Thomas55555/husqvarna_automower#443]
**Prerequirements**
[X] I have connected my mower(s) to the Automower Connect App
[X] I have connected my Husqvanra developers account to the Authentication API
[X] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
I recently added the GPS module to my 310, and it is working perfectly through the app. I have no problem adding the integration in HA with the API tokens, and it comes up straight away. The issue is that is does not update the sensors and the data without reloading the integration. When I reload, it pops up with the new information populated. The mobile app updates when things happen on the machine as expected.

**Expected behavior**
I would expect the HA integration entities to update at least somewhat timely like the mobile app does.

**Screenshots**
No screenshots, I can show that the entities doesn't update, but it's also described in the text above.

**Additional context**
Most others I know who are using the Automowers have the third party hardware installed, and so there is little information to find from people using this integration on the forums I use. I would therefore like to ask here if this is a bug more people have, or if it just hits me. I have no other issues with my HA install, and I am running about 30 other integrations flawlessly.

![Screenshot 2023-05-09 121148](https://github.com/Thomas55555/husqvarna_automower/assets/58890682/ee0f7b81-259d-4eab-bb8e-d0ae3aad391d)

**Comment by Mithrox** [comment]
"Good", at least its not just me.

**Comment by Thomas55555** [comment]
@remycrochon: Do the only update after a restart, or only once a day. Because all the statistics entities update normally once a day.

**Comment by Thomas55555** [comment]
@Mithrox: Can you share your device diagnostics?

**Comment by Mithrox** [comment]
Hi @Thomas55555. How do I gather the diagnostic for this specific integration/device?

**Comment by Mithrox** [comment]
> @remycrochon: Do the only update after a restart, or only once a day. Because all the statistics entities update normally once a day.

I did not check if it update once per day, but the entities for docked/undocked, mowing etc. isn't updating either, and they should update once there is a change. If not this will be a very useless integration, as I'd like to monitor how long it's from the station, if it's stuck etc.

**Comment by Thomas55555** [comment]
> Hi @Thomas55555. How do I gather the diagnostic for this specific integration/device?

On the integration page in ha click on download diagnostics

**Comment by remycrochon** [comment]
> @remycrochon: Do the only update after a restart, or only once a day. Because all the statistics entities update normally once a day.

Ok I'll check, but can't we reduce this update time

**Comment by Mithrox** [comment]
> > Hi @Thomas55555. How do I gather the diagnostic for this specific integration/device?
> 
> On the integration page in ha click on download diagnostics

Here is the integration file attached.
[config_entry-husqvarna_automower-8847b97b2104f7cdbed219c044604327.json.txt](https://github.com/Thomas55555/husqvarna_automower/files/11438708/config_entry-husqvarna_automower-8847b97b2104f7cdbed219c044604327.json.txt)

**Comment by Thomas55555** [comment]
> > @remycrochon: Do the only update after a restart, or only once a day. Because all the statistics entities update normally once a day.
> 
> Ok I'll check, but can't we reduce this update time

No, we poll it every 5 minutes, but the information on the Husqvarna server regarding this value are not updated in that intervall. Only once a day.

**Comment by Mithrox** [comment]
> > Here is the integration file attached. [config_entry-husqvarna_automower-8847b97b2104f7cdbed219c044604327.json.txt](https://github.com/Thomas55555/husqvarna_automower/files/11438708/config_entry-husqvarna_automower-8847b97b2104f7cdbed219c044604327.json.txt)
> 
> In the scope of your token is that part missing: `amc:api`. So websocket is not working. This avoids, that you get live updates. See the documenation hiere for more details: https://developer.husqvarnagroup.cloud/apis/automower-connect-api#websocket. But nevertheles ther should be update every 5 minutes. Can you check in your configuration if you've enabled `Disable Low energy` in the Integration config.
Sorry for late reply, I was travelling. Here is the config on the integration
![image](https://github.com/Thomas55555/husqvarna_automower/assets/58890682/8c2fc503-ff91-47ee-b232-b33fb5de3a5f)

Is there a way I can change the config you're referring to, to get the missing part in? I looked through the configuration manual on your page, and I cannot see I skipped any steps, but I may have without noticing. Please refer to how I can change it if you can.

**Comment by Mithrox** [comment]
I removed everything and started the process over again. Creating a new application and key/secret, and then after deleting the integration trying to set it up again. For some reason I now just get this when opening the link:

![image](https://github.com/Thomas55555/husqvarna_automower/assets/58890682/c5f78bea-96f3-49e3-a028-0a58bd53cc4c)

**Comment by Thomas55555** [comment]
> I removed everything and started the process over again. Creating a new application and key/secret, and then after deleting the integration trying to set it up again. For some reason I now just get this when opening the link:
> 
> ![image](https://user-images.githubusercontent.com/58890682/237880866-c5f78bea-96f3-49e3-a028-0a58bd53cc4c.png)
> 
> Can it be that it still kept the old key/secret somewhere even though I deleted the integration? Are there files somewhere that have this info and so prevents me from entering it anew?
> 
> Edit: I now removed the integration from HACS and restarted HA. I saw the folder was gone under custom_components. I then reinstalled it in HACS, restarted HA again and then tried the process all over again. But when I click on the integration, either via the link in the screenshot, or manually by searching for it and then clicking it, it skips straight to the URL: https://api.authentication.husqvarnagroup.dev/xxxxxxxx (edited).
> 
> ![image](https://user-images.githubusercontent.com/58890682/237883753-f472c601-c8cf-4fae-a0bd-4ceb82801c95.png)
> 
> Is there any configuration I can manually delete somewhere to make sure I start completely fresh with the new key/secret I created on the developer portal?

Yes, it's basic HA knwoledge. But if you don't no, here it is described:
https://github.com/Thomas55555/husqvarna_automower#remove-credentials

**Comment by Mithrox** [comment]
> Yes, it's basic HA knwoledge. But if you don't no, here it is described: https://github.com/Thomas55555/husqvarna_automower#remove-credentials

Lucky me then apparently, cause with my now 42 (!) integrations, I have never had to remove a single credential before, and these two are the only ones in that list. But now I know. I will remove, and make sure I start completely fresh with the integration, and then see if the settings get correct. Thank you.

![image](https://github.com/Thomas55555/husqvarna_automower/assets/58890682/ae3f477b-de44-4e55-8530-d503697a0df6)

**Comment by Mithrox** [comment]
It now receives updates when things happen, so it looks to be working properly now.

Thank you for all your help and patience, looking forward to automating some things with input from the mower.
