### ISSUE TITLE
Not all mower models support updating the mowing schedule

### ISSUE THREAD

**Issue by OEHC** [Thomas55555/husqvarna_automower#452]
**Prerequirements**
[:heavy_check_mark: ] I have connected my mower(s) to the Automower Connect App
[:heavy_check_mark: ] I have connected my Husqvanra developers account to the Authentication API
[:heavy_check_mark: ] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
When trying to update the mowing schedule using the `husqvarna_automower.calendar` service, the schedule remains unchanged and an error is logged:
```
Command couldn't be sent to the command que: 400, message='Bad Request', url=URL('https://api.amc.husqvarna.dev/v1/mowers/20ea32ed-8e38-461b-8b0e-b5a48026dd19/calendar') 
```

**Expected behavior**
I expected the schedule to be updated or the integration to not expose the service if it is not compatible with my mower.

**Additional context**
Debug log of the request:
```
2023-05-16 14:24:14.594 DEBUG (MainThread) [custom_components.husqvarna_automower.vacuum] start in minutes int: 720
2023-05-16 14:24:14.595 DEBUG (MainThread) [custom_components.husqvarna_automower.vacuum] end in minutes: 1080
2023-05-16 14:24:14.750 DEBUG (MainThread) [aioautomower.rest] Mower Action URL: https://api.amc.husqvarna.dev/v1/mowers/20ea32ed-8e38-461b-8b0e-b5a48026dd19/calendar
2023-05-16 14:24:14.751 DEBUG (MainThread) [aioautomower.rest] Sent payload: {"data": {"type": "calendar", "attributes": {"tasks": [{"start": 720, "duration": 360, "monday": true, "tuesday": true, "wednesday": true, "thursday": true, "friday": true, "saturday": true, "sunday": true}]}}}
2023-05-16 14:24:14.751 DEBUG (MainThread) [aioautomower.rest] Resp status mower command: 400
2023-05-16 14:24:14.751 ERROR (MainThread) [custom_components.husqvarna_automower.vacuum] Command couldn't be sent to the command que: 400, message='Bad Request', url=URL('https://api.amc.husqvarna.dev/v1/mowers/20ea32ed-8e38-461b-8b0e-b5a48026dd19/calendar')
```

I've dug further and tried to update the mowing schedule using [Husqvarna's OpenAPI example](https://developer.husqvarnagroup.cloud/apis/automower-connect-api#openapi). Here it failed as well with the following response:
```
{
  "errors": [
    {
      "id": "1e731fe0-ff0a-4bfc-b87b-4d233f22625f",
      "status": "400",
      "code": "illegal.argument",
      "title": "Illegal argument",
      "detail": "This mower use missions and can not be updated by this endpoint"
    }
  ]
}
```

This seems related to #317, in which we discovered that some models (405X, 415X and 435X AWD) cannot update the cutting height through the API, as these mowers support different cutting height for different areas (called missions). Indeed, my 415X also support different schedules for each of the areas, and thus cannot change the schedule through the API for now at least.

I don't know if this integration can dynamically expose the `calendar` service only if the mower model supports it. If not, I think this information should at least be mentioned in the README.

**Comment by Thomas55555** [comment]
As far as I know, it's not recognisable, if the mower is on mission. I could send once a day a command for a calendar change and have a look at the result. But that's not the best way I think. Can you tell me more about mission. My mower doesn't have this feature. Is the mower mowing all day and night?

**Comment by OEHC** [comment]
From my understanding, this is a matter of whether the mower _supports_ missions. I'll be happy to test this hypothesis in a couple of weeks. As far as I know, I cannot "disable" the use of missions on my 415X. If this is indeed true, the integration could determine if the calendar update is supported directly from the mower model.

> Can you tell me more about mission. Is the mower mowing all day and night?

My mower has a schedule of mowing three days a week for nine hours. I have not defined any custom zones or customized the default generated GPS-assisted map in any way. But my mower _supports_ that I define separate zones within my map and each zone can have a different schedule and cutting height.

[Quoting Husqvarna support](https://github.com/ice987987/ioBroker.husqvarna-automower/issues/23#issuecomment-1130223083):
> Currently the Automower Connect API does not support missions. Missions can be created in the Automower connect app in the map view by creating an area where the mower can work in. You can create multiple work areas and for every area a mission will be created. The mission contains the information like name and cutting height. An area/mission can have its own cutting height. It will be available soon. For missions cutting height need to be set per mission.
Supported models are 405X, 415X and 435X AWD.

My guess is that because my mower supports zones/missions, it always operates using missions albeit my mower only have the default zone.


Currently my mower is remapping the lawn as I've made changes to the boundary cable and deleted it's old map. When it is finished, I'll be happy to test if I can somehow disable the use of "missions" and thus make the API call work, but I suspect that the models 405X, 415X and 435X AWD always use missions and thus cannot use the current API to update cutting height or schedule.

**Comment by tuupos** [comment]
Hello OEHC,

as a 415x owner, did you make it work after 2 weeks? I also would like to integrate the different schedules of the missions in homeassistant (e.g. only cutting the frontyard from dawn till 0900u) after 0900u let the GPS figure out where to cut.

Maybe I just have to be patient untill husqvarna updates there API.

**Comment by OEHC** [comment]
My 415X is still remapping the lawn so I've got no updates yet. I'll get back as soon as it is done and I have tested whether disabling "GPS assisted navigation" makes any difference.

It would be great if Husqvarna updated the API. It is hard to find any information on their roadmap except for the linked answer above.

**Comment by robertoash** [comment]
> My 415X is still remapping the lawn so I've got no updates yet. I'll get back as soon as it is done and I have tested whether disabling "GPS assisted navigation" or something similar makes any difference.
> 
> It would be great if Husqvarna updated the API. It is hard to find any information on their roadmap except for the linked answer above.

Any news? Did disabling GPS assisted navigation make a difference?

**Comment by OEHC** [comment]
My mower is still remapping my lawn and I would rather not disturb it too much until it is done, at the risk of having to start over. So I have no updates yet. I guess my initial estimate of a couple of weeks for the remapping were quite optimistic.
If anyone else is able to do some testing in the meantime, you are more then welcome to test the hypothesis that 405X, 415X and 435X AWD always use missions and this cannot be disabled using any combination of settings.
As soon as the mapping is complete I'll start testing :)

**Comment by OEHC** [comment]
Yay, the mapping finished today. I've tried disabling the "Settings -> Installation -> Lawn coverage -> GPS assisted navigation" as well as define multiple work areas and stay-out zones and delete them all again. No matter the combination I used, the calendar endpoint threw the illegal argument exception because the mower use missions.
I've sent an email to the Husqvarna devs, asking if it is possible to disable the use of missions on a 405X, 415X and 435X AWD.

**Comment by tuupos** [comment]
Is it necessary to ask for disabling the missions? I would rather see the missions (or more schedules is what it is? ) added. 
created in the app 2 schedules. (so those are different missions?)

schedule 1 for the whole yard running from 0900h till dusk/sunset. (in the below image still old as it shows 0.00h)
schedule 2 only for the frontyard running from 0600h till 0900h
_(because @ the frontyard there are no sleeping rooms we wont be woken up by the mower between 6 & 9am)_

Those 2 schedules can be found back in home assistants calendar: 
![Schermafbeelding 2023-06-15 114508](https://github.com/Thomas55555/husqvarna_automower/assets/54961501/fb5df290-c095-4d78-87df-35febe6b61ce)'

But throws the known error message : _Command couldn't be sent to the command que: 400, message='Bad Request', url=URL('https://api.amc.husqvarna.dev/v1/mowers/XXXX/calendar')_ when I try to change them.

I will write also an email at the developers @ husqvarna to see if there is an indication of when the api supports multipele schedules/missions.

I'm not a programmer myself just an enthousiastich hobbiest. I can change code but Im nowhere @ developing my own or even know how an API works.

**Comment by Din-BH** [comment]
No matter how we turn I turn this around, we should get support from Husqvarna for zones and respective schedules from the API. I have two distinct areas mapped, and I am using schedules to make sure that the area being watered is not selected for cutting. I don't want to turn of zones. Wonder if it helps our cause if we all send emails to Husqvarna, letting them know this is important and that they need to put effort in making essential APIs available...

**Comment by Din-BH** [comment]
Perfect timing. I was just about to hit send on my email to them, but I will hold off then. Good news! I assume the same will enable setting cutting hight as well on movers with area support, since those are also area dependent in 405X etc
