### ISSUE TITLE
Problem on installation : "Client not found"

### ISSUE THREAD

**Issue by Jex2512** [Thomas55555/husqvarna_automower#453]
Hello,

I've a problem with this integration. I've already add this integration long time ago (last summer) and it was ok. Today, i want to update it (2023.5.0) and i have this problem :

- Install via HACS is ok
- Configuration of Husqvarna Developer Portal seem to be ok
- When i want to add this integration to my home assistant, i've a window who say me to open a web site. When i click on "Open the website", i've this error :
- 
![Error](https://github.com/Thomas55555/husqvarna_automower/assets/10290088/eaf20166-70d0-475a-9bb7-e8808ffbe774)

I've already uninstall integration via HACS, restart home assistant, recretae configuration of Husqvarna Developer Portal.

![image](https://github.com/Thomas55555/husqvarna_automower/assets/10290088/b08e9edd-6d51-427d-89c2-d4686ebc4d06)

Thanks U

**Comment by Thomas55555** [comment]
Can you try removing your credentials. See here:
https://github.com/Thomas55555/husqvarna_automower/issues/443#issuecomment-1545200056

**Comment by Jex2512** [comment]
It works ! Thanks you for your help
