### ISSUE TITLE
Map image stays black after inserting map image

### ISSUE THREAD

**Issue by Marc1200** [Thomas55555/husqvarna_automower#456]
**Prerequirements**
[ ] I have connected my mower(s) to the Automower Connect App
[ ] I have connected my Husqvanra developers account to the Authentication API
[ ] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
When using camera entity it stays at black image, it should display the default image. When i insert an new image it also stays black

**Expected behavior**

**Screenshots**
![image](https://github.com/Thomas55555/husqvarna_automower/assets/68737063/2bc7f6e8-216f-455b-a999-31e579d640b9)

**Additional context**

**Comment by Din-BH** [comment]
Try using the full path for the image; e.g. instead of /local/... or similar, use /config/www/... At least that way I got my setup working.

**Comment by Marc1200** [comment]
Yes i did but i now know whats going on, my mower has no GPS, it's the Husqvarna Automower Aspire R4. I saw in the log that the integration was trying to fetch coordinates, it gave an error.
