### ISSUE TITLE
Entities does not update

### ISSUE THREAD

**Issue by theailer** [Thomas55555/husqvarna_automower#458]
**Prerequirements**
[x] I have connected my mower(s) to the Automower Connect App
[x] I have connected my Husqvanra developers account to the Authentication API
[x] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
Entities only update when reloading the integration

**Expected behavior**
Should be frequent updates

**Screenshots**
![image](https://github.com/Thomas55555/husqvarna_automower/assets/5675706/16a63ed9-ac98-4104-8606-ae0fd899b574)

**Comment by Thomas55555** [comment]
Please try version 2023.5b3 and have a look for "repairs" in home assistant

**Comment by theailer** [comment]
I tried both 2023.5.1b3 and 2023.5.1b4 but problem seems to persist unfortunately.
There were also nothing under repairs.
How often should it update? Battery state is currently sitting at 18minutes ago same as the gps coordinates.

**Comment by Thomas55555** [comment]
Can you download the device diagnostics and have a look for the token scope, like described in this issue #443

**Comment by Thomas55555** [comment]
The battery entity is normally updating every five minutes.

**Comment by theailer** [comment]
This is what's on the device diags unfortunately.


500 Internal Server Error

Server got itself in trouble

**Comment by theailer** [comment]
I’ve also removed the integration completely and reinstalled but still the same error.

**Comment by theailer** [comment]
[config_entry-husqvarna_automower-4d15a74d5db4146f39623ca6657d57ed.json.txt](https://github.com/Thomas55555/husqvarna_automower/files/11582959/config_entry-husqvarna_automower-4d15a74d5db4146f39623ca6657d57ed.json.txt)

With the latest version it was possible to create a device diag file

**Comment by theailer** [comment]
Hi
The fault is back again, it will only update once after reloading the addon.

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.7.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.4",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Stockholm",
    "os_name": "Linux",
    "os_version": "6.1.21-v8",
    "supervisor": "2023.07.1",
    "host_os": "Home Assistant OS 10.3",
    "docker_version": "23.0.6",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "husqvarna_automower": {
      "version": "2023.8.0b0",
      "requirements": [
        "aioautomower==2023.7.1",
        "geopy>=2.1.0",
        "numpy>=1.21.6",
        "Pillow>=9.1.1",
        "Shapely>=1.8.2"
      ]
    },
    "nordpool": {
      "version": "0.0.14",
      "requirements": [
        "nordpool>=0.2",
        "backoff"
      ]
    }
  },
  "integration_manifest": {
    "domain": "husqvarna_automower",
    "name": "Husqvarna Automower",
    "codeowners": [
      "@Thomas55555"
    ],
    "config_flow": true,
    "dependencies": [
      "application_credentials",
      "my",
      "schedule"
    ],
    "documentation": "https://github.com/Thomas55555/husqvarna_automower",
    "integration_type": "hub",
    "iot_class": "cloud_push",
    "issue_tracker": "https://github.com/Thomas55555/husqvarna_automower/issues",
    "loggers": [
      "aioautomower",
      "geopy",
      "numpy",
      "Pillow"
    ],
    "requirements": [
      "aioautomower==2023.7.1",
      "geopy>=2.1.0",
      "numpy>=1.21.6",
      "Pillow>=9.1.1",
      "Shapely>=1.8.2"
    ],
    "version": "2023.8.0b0",
    "is_built_in": false
  },
  "data": {
    "config_entry": {
      "entry_id": "4d15a74d5db4146f39623ca6657d57ed",
      "version": 4,
      "domain": "husqvarna_automower",
      "title": "husqvarna_automower",
      "data": {
        "auth_implementation": "husqvarna_automower",
        "token": {
          "access_token": "**REDACTED**",
          "scope": "iam:read amc:api",
          "expires_in": 86399,
          "refresh_token": "**REDACTED**",
          "provider": "husqvarna",
          "user_id": "78a90933-2b20-449d-b2bc-ff0a7ba1b751",
          "token_type": "Bearer",
          "expires_at": 1689937461.241023,
          "status": 200
        }
      },
      "options": {
        "54dd2b7b-6a92-426b-97da-1eccd2c621f4": {
          "gps_top_left": "",
          "gps_bottom_right": "",
          "mower_img_path": "/config/custom_components/husqvarna_automower/resources/mower.png",
          "map_img_path": "/config/custom_components/husqvarna_automower/resources/map_image.png",
          "map_img_rotation": 0,
          "map_path_color": [
            255,
            0,
            0
          ],
          "home_location": ""
        }
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": "husqvarna_automower",
      "disabled_by": null
    },
    "data_of_all_mowers": [
      {
        "type": "mower",
        "id": "54dd2b7b-6a92-426b-97da-1eccd2c621f4",
        "attributes": {
          "system": {
            "name": "Automower",
            "model": "HUSQVARNA AUTOMOWER\u00ae 430X",
            "serialNumber": 201709977
          },
          "battery": {
            "batteryPercent": 99
          },
          "mower": {
            "mode": "MAIN_AREA",
            "activity": "NOT_APPLICABLE",
            "state": "ERROR",
            "errorCode": 2,
            "errorCodeTimestamp": 1689918122000
          },
          "calendar": {
            "tasks": [
              {
                "start": 0,
                "duration": 1439,
                "monday": true,
                "tuesday": true,
                "wednesday": true,
                "thursday": true,
                "friday": true,
                "saturday": true,
                "sunday": true
              }
            ]
          },
          "planner": {
            "nextStartTimestamp": 0,
            "override": {
              "action": "NOT_ACTIVE"
            },
            "restrictedReason": "NOT_APPLICABLE"
          },
          "metadata": {
            "connected": true,
            "statusTimestamp": 1689928651193
          },
          "positions": "**REDACTED**",
          "statistics": {
            "numberOfChargingCycles": 1282,
            "numberOfCollisions": 35336,
            "totalChargingTime": 3981600,
            "totalCuttingTime": 11642400,
            "totalRunningTime": 12340800,
            "totalSearchingTime": 698400
          },
          "cuttingHeight": 5,
          "headlight": {
            "mode": "EVENING_AND_NIGHT"
          }
        }
      }
    ]
  }
}

**Comment by theailer** [comment]
With 2023.8.0b2 it works again
