### ISSUE TITLE
Support for Sileno Life

### ISSUE THREAD

**Issue by kizio1000** [Thomas55555/husqvarna_automower#479]
**Prerequirements**
[x ] I have connected my mower(s) to the Automower Connect App
[x] I have connected my Husqvanra developers account to the Authentication API
[x] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
I have configured Gardena integration for HA by using Husqarna developer portal and API but presently Gardena integration for HA does not support map display for newest Sileno Life Smart LONA models which are another iteration of Husqarna movers under their Gardena brand. Therefore I have installed Husqarna automover integration in order to gain options that are not present in Gardena integration. 

Everything went ok on installation and configuration but there is no entity created in the system, similar to [#426 ](https://github.com/Thomas55555/husqvarna_automower/issues/426).

I have tried to create separate application on Husqarna dev portal with separate access to API - no change
I have tried to remove integration and redownload and configure over as suggested in #426  - no change
I do not see any errors in HA log regarding this 

**Expected behavior**
Mover entity will be shown in HA

**Screenshots**
![Screenshot 2023-06-05 081747](https://github.com/Thomas55555/husqvarna_automower/assets/76654878/8cf73c75-14e7-41b6-a1cc-446756d148e9)

**Additional context**
Map for my mover is w/o problem shown in Gardena app on Android and Gardena integration in Home Assistant is using exactly the same API on Husqarna portal for developers. Therefore I presume that it should be possible to use this integration to gain full functionality of newest Gardena movers that are based on Husqarna models.

**Comment by Jogge** [comment]
> Sorry, but this integration is only for Husqvarna mowers.

Why? If integration is almost identical, why not also support Gardena?

**Comment by Thomas55555** [comment]
Only the authentication part is the same. The rest of the API looks completely different to me.
Tried this one?
https://github.com/py-smart-gardena/hass-gardena-smart-system
