### ISSUE TITLE
Broken by 2023.6.1

### ISSUE THREAD

**Issue by GregoryGHarding** [Thomas55555/husqvarna_automower#486]
my HA install update to 6.1 from 6 overnight and had broken both my husqvarna integration, and my xiaomi integration. 

there was a known issue submitted for the xiaomi integration regarding some lines in .py files related to import asyncio @asyncio.coroutine but i could not remedy the husq integration with this fix.

**Comment by prairiesnpr** [comment]
Any log? I run a fork of this project and not seeing any errors on 6.1.

**Comment by bialeta** [comment]
After upgrade to 6.1 (Python 3.11.4), log:
2023-06-10 08:45:51.941 WARNING (MainThread) [homeassistant.config_entries] Config entry 'husqvarna_automower' for husqvarna_automower integration could not authenticate
2023-06-10 08:46:03.990 DEBUG (MainThread) [custom_components.husqvarna_automower] Exception in async_setup_entry: Cannot connect to host api.amc.husqvarna.dev:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]
2023-06-10 08:46:03.992 DEBUG (MainThread) [custom_components.husqvarna_automower] Finished fetching husqvarna_automower data in 0.090 seconds (success: False)
2023-06-10 08:46:03.992 WARNING (MainThread) [homeassistant.config_entries] Config entry 'husqvarna_automower' for husqvarna_automower integration could not authenticate

**Comment by prairiesnpr** [comment]
@bialeta you likely have a separate and unrelated issue. Would be best to create your own issue.  That said, it's very unlikely for an ssl certificate verification failure to be the fault of the integration.  That's likely a system configuration issue or an issue with the Husqvarna host.  Not seeing any issues on my side with Husqvarna, my prod and dev instances, both on 2023.6.1 are connected without issue. SSL cert is valid, might be worth asking the home assistant community, especially if you are seeing issues with other cloud based integrations.

**Comment by bialeta** [comment]
Ok, thank you, I`ll try to find another reason of this issue if you are sure it`s not linked with your integration and hass/python upgrade.

**Comment by Thomas55555** [comment]
I also don't think it's related, because HA 2023.6.0 was already on python 3.11

**Comment by GregoryGHarding** [comment]
> Any logs? I run a fork of this project and I'm not seeing any errors on 2023.6.1.

I am not able to access logs ATM. But I will post what I can when I have access. In the mean time, what bialeta posted looks firmiliar, given the async error in their log

**Comment by GregoryGHarding** [comment]
> Any logs? I run a fork of this project and I'm not seeing any errors on 2023.6.1.

```
2023-06-10 12:27:59.697 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up husqvarna_automower platform for binary_sensor
Traceback (most recent call last):
  File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/husqvarna_automower/binary_sensor.py", line 25, in async_setup_entry
    for idx, ent in enumerate(coordinator.session.data["data"])
```

**Comment by bialeta** [comment]
I`m trying to downgrade HA and python to see if error is seen again in different scenarios, in few hours I will get the answer.

**Comment by slovdahl** [comment]
@GregoryGHarding A similar issue is being discussed in #426. I'm still on 2023.5 and had the exact same issue.

**Comment by bialeta** [comment]
Deleting authorization and even removing and reinstalling this integration does not work. Anyway, I made some work last 2 days and nights off course :-) with testing this crash and I have some findings:
**HA=2023.5.2; Python=3.10.11**
No problem with husqvarna, works like a charm.
"home_assistant": {
    "installation_type": "Home Assistant Core",
    "version": "2023.5.2",
    "dev": false,
    "hassio": false,
    "virtualenv": true,
    "python_version": "3.10.11",
    "docker": false,
    "arch": "armv7l",
    "timezone": "Europe/Warsaw",
    "os_name": "Linux",
    "os_version": "6.1.25-v7l+",
    "run_as_root": false
"husqvarna_automower": {
      "version": "2023.6.0b1",
      "requirements": [
        "aioautomower==2023.4.4",
        "geopy>=2.1.0",
        "numpy>=1.21.6",
        "Pillow>=9.1.1"

**HA=2023.6.1; Python=3.10.11**
No problem with install/upgrade HA and husqvarna, after hass start only warn of Python upgrade to 3.11 with versions higher than 2023.8.*

**HA=2023.5.4; Python=3.11.4**
After upgrade to Python 3.11 or even 3.12, husqvarna does not work, no matter what version of HA is installed.

I guess the issue is in Python higher than 3.11.  My installation is core installation on RPi 4, I don`t know how it works on other types of instllations.
There are other issues linked with HA depending on Python version (ffmpeg/ha-av/aiohttp/frozenlist), but not for this topic. If anyone is iterested in I can share my 2 days of fight with it. For instance once ha-av is needed in v. 10.0.0 other in v. 10.1.0, depending on version of ha-av different version of ffmpeg is mandatory.

**Comment by prairiesnpr** [comment]
@bialeta My production instance is running core 2023.6.1 on top of python 3.11.3 in a venv.  It's likely that you are running into open ssl issues on the base system.  As you know, trying to run core in a venv is a huge pain, especially with how many packages are out of date in raspbian.  I too was bit by the ha-av issue and had to recompile ffmpeg in order to move to 2023.6.1 on the pi. My guess is, if you tried to retrieve the api url directly from the venv, you would see the same error.  I would start troubleshooting there.

**Comment by bialeta** [comment]
Got that, problem solved.
Few weeks ago I had to recompile openssl by hand with prefix /usr/local/ssl, everything went smoothly and my goal was reached, there were no problems with openssl so far. After moving HA 2023.5.* to 2023.6.* with Pytnhon upgrade to 3.11 arised problem described above.
Looking at log output with SSLCertVerificationError and thanks for suggestion from @prairiesnpr I started to look for solution in openssl.
Openssl recompilation gave nothing, but looking in the file tree I noticed /usr/local/ssl/certs is empty. Removed certs from this location and linked here /etc/ssl/certs. After that everything came to it`s place. Now husqvarna integration works again with HA.
Thanks everyone for suggestions.

**Comment by GregoryGHarding** [comment]
> @GregoryGHarding A similar issue is being discussed in #426. I'm still on 2023.5 and had the exact same issue. Solved it by deleting the integration and the authorization key, and adding it again.

this worked. this bug still needs to be worked out though.

**Comment by BernieV1977** [comment]
> 


@bialeta 
> Openssl recompilation gave nothing, but looking in the file tree I noticed /usr/local/ssl/certs is empty. Removed certs from this location and linked here /etc/ssl/certs. After that everything came to it`s place
What do you men by tihs? Did you moved these files from /etc/ssl/certs to /usr/local/ssl/certs?

**Comment by robinostlund** [comment]
@BernieV1977 have you tried this command  `update-ca-certificates` ?

**Comment by BernieV1977** [comment]
> @BernieV1977 have you tried this command `update-ca-certificates` ?

Yes I did and I did also apt-update and apt-upgrade after that.

**Comment by bialeta** [comment]
Openssl by hand recompilation in typical configuration puts files in /usr/local/ssl 
After that one have to show new shared libraries /usr/local/ssl/lib for ldconfig for instance in /etc/ld.so.conf.
Anyway /usr/local/ssl/certs is empty after compilation. Linking /etc/ssl/certs to /usr/local/ssl/certs makes the work.
ln -s /etc/ssl/certs /usr/local/ssl/certs is enaugh so far. 
I did not try to update certificates

**Comment by bialeta** [comment]
Can you provide few rows of output:
ls -la /etc/ssl/certs 
and
ls -la /usr/local/ssl/certs

**Comment by BernieV1977** [comment]
I checked it and yes, I think there is something wrong.
After linking I have /etc/ssl/certs/certs
Should I do in my case ln -s /etc/ssl/certs /usr/local/ssl

Results

 ls -la /etc/ssl/certs
totaal 628
drwxr-xr-x 2 root root  20480 13 jul 12:45  .
drwxr-xr-x 4 root root   4096  6 jul 09:07  ..
lrwxrwxrwx 1 root root     23 10 jul 10:06  002c0b4f.0 -> GlobalSign_Root_R46.pem
lrwxrwxrwx 1 root root     45 10 jul 10:06  02265526.0 -> Entrust_Root_Certification_Authority_-_G2.pem
lrwxrwxrwx 1 root root     27 10 jul 10:06  062cdee6.0 -> GlobalSign_Root_CA_-_R3.pem
lrwxrwxrwx 1 root root     25 10 jul 10:06  064e0aa9.0 -> QuoVadis_Root_CA_2_G3.pem


---------------------------------------

ls -la /usr/local/ssl/certs
totaal 8
drwxr-sr-x 2 root staff 4096 14 jul 08:21 .
drwxr-sr-x 5 root staff 4096  4 jun  2021 ..
lrwxrwxrwx 1 root staff   14 14 jul 08:21 certs -> /etc/ssl/certs

**Comment by bialeta** [comment]
Ok, I assume you compiled openssl by hand.
When you look at /usr/local/ssl/certs you can see nothing, seems the same problem like mine.
Remove catalog **certs** from **/usr/local/ssl/** and link **/etc/ssl/certs** to **/usr/local/ssl/**, you have to see catalog **certs** in **/usr/local/ssl/**. When you list files in **/usr/local/ssl/certs** you have to see the same files like in **/etc/ssl/certs**.
All commands below:
_sudo rm -r  /usr/local/ssl/certs
sudo ln -s /etc/ssl/certs /usr/local/ssl/certs_
Check somewhere in **/etc/ld.so.conf.d/** if you have a record **/usr/local/ssl/lib**, usually it is added in **openssl-3.0.7.conf** by openssl after installation.

**Comment by BernieV1977** [comment]
Yes, that did the trick!!
Thx @bialeta !
