### ISSUE TITLE
Room for improved translations

### ISSUE THREAD

**Issue by astrandb** [Thomas55555/husqvarna_automower#489]
Thank you for this integration, it works like a charm for my two mowers.

I can see that there is some room for improving the translations, especially there is no translation of entity names. I would be happy to start to work on entity name translations. Would you accept a PR on this topic?

And a few comments:
strings.json and strings.vacuum.json are not used in custom components. They are used as templates for Lokalise when core is built. These files can be deleted - and recreated/updated if you submit the integration for official inclusion  in HA core.

I foung a little typo in the about field on the front page: Should be Husqvarna

**Comment by Thomas55555** [comment]
Yes, you can.
