### ISSUE TITLE
HA Integration

### ISSUE THREAD

**Issue by aaron92hunt** [Thomas55555/husqvarna_automower#496]
**Prerequirements**
[X ] I have connected my mower(s) to the Automower Connect App
[ ] I have connected my Husqvanra developers account to the Authentication API
[ ] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**

I'm brand new to HA like just started today. And I cannot seem to get the Husqvarna integration 

**Expected behavior**

I expected to be able to find the integration under add ons

**Screenshots**

**Additional context**
I'm really not sure what I'm doing. I would appreciate any kind of assistance.

**Comment by Thomas55555** [comment]
After installation of this integration according to the readme you have to look in integrations not add-ons

**Comment by aaron92hunt** [comment]
Yeah I can’t even install the integration because I have determined that the file config/home-assistant.log does not exist. On Jun 25, 2023, at 5:48 AM, Thomas55555 ***@***.***> wrote:﻿
After installation of this integration according to the readme you have to look in integrations not add-ons
