### ISSUE TITLE
Feature request: Enable removing credentials

### ISSUE THREAD

**Issue by Din-BH** [Thomas55555/husqvarna_automower#507]
**Describe the issue**
For some reason my credentials stored in HA for Automower were corrupted. I don't know if it is Husqvarna, HA or (unlikely) the extension itself, but they are no longer usable as they suddenly started generate "user not found" errors. Solution is to replace credentials. I can add a new set of credentials, but having the old credentials in place seems to result in unstable extension operation.
The old credentials cannot be removed without removing the whole extension: HA says "Removing Application Credential failed:
Cannot delete credential in use by integration husqvarna_automower" when trying.

**Feature proposal**
When a set of keys is not in use or not working (such as generating errors like above), or when the extension is disabled, or something similar, the extension should "release" the credentials so that they can be removed. This would allow for issue management, and a clear and simple path forward for cases such as #426.

**Comment by Din-BH** [comment]
Update; I reconfigured the extension, turned off the mower and waited. Then I was able to remove the faulty credentials. When can credentials be removed?

**Comment by Thomas55555** [comment]
It is not possible to add this in the custom component. This is done by the application credentials integration of home assistant.
To change the credentials you have to remove the integration and then delete them.

**Comment by Din-BH** [comment]
Well, apparently not quite so, since I was able to remove one of them without removing the integration. Seems there should be a logic to when a credential is 'in use' by an integration and when not.

**Comment by robinostlund** [comment]
@Din-BH if you need to fix your credentials or change them you can stop homeassistant and then modify the credentials manually in .storage/application_credentials

**Comment by Din-BH** [comment]
> @Din-BH if you need to fix your credentials or change them you can stop homeassistant and then modify the credentials manually in .storage/application_credentials

Thanks for the tip. Not super easy to edit files while HA is stopped on a HA OS installation and not quite trivial for the general user base? I assume it might be possible to edit also while the OS is running and then just restart? Still think if there would be a way to make the credentials 'inactive' in the integration itself that would be the best way - then the integration could advice the user of how to fix the issue when issues with credentials a are detected.

Then why this happened in the first place is another issue. I didn't do anything with this integration before this issue occured, but I did just add credentials for Netatmo... Sounds like that might be a potential HA issue.
