### ISSUE TITLE
Submit multiple calendars

### ISSUE THREAD

**Issue by belinea4071** [Thomas55555/husqvarna_automower#508]
**Prerequirements**
[ x] I have connected my mower(s) to the Automower Connect App
[ x] I have connected my Husqvanra developers account to the Authentication API
[ x] I have connected my Husqvarna developers account to the Automower Connect API

**Current behavior**
I can according to the documentation transmit one calendar.
[Services](https://github.com/Thomas55555/husqvarna_automower#services)

`service: husqvarna_automower.calendar 

data:
  start: '7:45:00'
  end: '11:30:00'
  monday: true
  tuesday: true
  wednesday: true
  thursday: true
  friday: true
  saturday: false
  sunday: false
target:
  entity_id: vacuum.automower`

This works as described. I would like an extension of the function.

**Feature proposal**
I would like to send several calendar entries with one service call as the Automower API allows. So I don't have to update the calendar every half day and could do the update once a week.

`service: husqvarna_automower.calendar 

data:
[{
  start: '7:45:00'
  end: '11:30:00'
  monday: true
  tuesday: true
  wednesday: true
  thursday: true
  friday: true
  saturday: false
  sunday: false
},
{
  start: '17:10:00'
  end: '19:30:00'
  monday: true
  tuesday: true
  wednesday: true
  thursday: true
  friday: true
  saturday: false
  sunday: false
}]
target:
  entity_id: vacuum.automower`

[API Docu: Update mower schedule](https://developer.husqvarnagroup.cloud/apis/automower-connect-api?tab=readme) 

**Screenshots**
API Docu: Update mower schedule
![Automower_docu](https://github.com/Thomas55555/husqvarna_automower/assets/51459140/c87175fa-9f44-44fa-b7e6-2293f924a06a)
Future, HomeAssistant Service Call
![HA Service Cal](https://github.com/Thomas55555/husqvarna_automower/assets/51459140/d2ba17e4-305a-4eec-ba9f-851bfc44801c)

**Comment by Thomas55555** [comment]
I limited this to one schedule, because otherwise I would have to extend an infinite number of possible schedules. But you can use this command. You only have to do a little bit templating with the times (minutes from midnight instead of normal times):
```
service: husqvarna_automower.custom_command
data:
  command_type: calendar
  json_string: >-
    { "data":{ "type":"calendar", "attributes":{ "tasks":[ { "start":450,
    "duration":240, "monday":false, "tuesday":true, "wednesday":false,
    "thursday":false, "friday":false, "saturday":false, "sunday":false }, {
    "start":1035, "duration":135, "monday":true, "tuesday":false,
    "wednesday":false, "thursday":false, "friday":false, "saturday":false,
    "sunday":false } ] } } }
target:
  entity_id: vacuum.bruno
```

**Comment by Thomas55555** [comment]
Or, maybe the schedule function will help you:
https://github.com/Thomas55555/husqvarna_automower/pull/345#issue-1364766583

**Comment by belinea4071** [comment]
Thanks a lot for your help. I understand your objection, I didn't think of that.
I like both suggestions. For my purpose I will take variant with the custom_command. With this command, I can dynamically calculate the end times based on the sunset.
