### ISSUE TITLE
State value 'all_missions_completed' missing

### ISSUE THREAD

**Issue by Gloomyeye** [Thomas55555/husqvarna_automower#515]
**Prerequirements**
[ X ] I have connected my mower(s) to the Automower Connect App
[ X ] I have connected my Husqvanra developers account to the Authentication API
[ X ] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**

A warning will be created in the log. I don't know when exactly the warning will be created. However, my feeling is that this state was created when I start the mower with the option "30 minutes" in the Husqvarna App. After 30 minutes the mower stopped.

**Expected behavior**

Warning will not happen. The given state is known.

**Screenshots**

**Additional context**

```
Logger: homeassistant
Source: components/sensor/__init__.py:572 
First occurred: 16:56:36 (1 occurrences) 
Last logged: 16:56:36

Error doing job: Exception in callback AutomowerEntity.async_added_to_hass.<locals>.<lambda>({'data': [{'attributes': {'battery': {'batteryPercent': 95}, 'calendar': {'tasks': [{...}]}, 'cuttingHeight': 4, 'headlight': {'mode': 'EVENING_AND_NIGHT'}, ...}, 'id': 'd9b9be3b-d93...-00ff25297cd5', 'type': 'mower'}]}) at /config/custom_components/husqvarna_automower/entity.py:53
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/husqvarna_automower/entity.py", line 53, in <lambda>
    lambda _: self.async_write_ha_state(), schedule_immediately=True
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 572, in state
    raise ValueError(
ValueError: Sensor sensor.gar_mower_husky_problem provides state value 'all_missions_completed', which is not in the list of options provided
```

**Comment by Thomas55555** [comment]
Can you download the diagnostics and share it here?
Do you have a mower which supports missions?

**Comment by Gloomyeye** [comment]
The diagnostics: 
[config_entry-husqvarna_automower-8fc96a4b6238ec48f1603de0bcc30489.json.txt](https://github.com/Thomas55555/husqvarna_automower/files/12064721/config_entry-husqvarna_automower-8fc96a4b6238ec48f1603de0bcc30489.json.txt)

I don't know if my mower (HUSQVARNA AUTOMOWER® 415X) supports missions ;) Where can I check this?

**Comment by Thomas55555** [comment]
These support missions: Automower®-Models 405X, 415X, 430X NERA, 450X NERA, 435X AWD and 535 AWD
Is you mower still in this error state? I expected to see something with the missions in the diagnostics.

**Comment by Gloomyeye** [comment]
No, the mower has no error anymore. I started the option with 30min mowing today and here are three diagnostics:

1. Direct after starting: [config_entry-husqvarna_automower-8fc96a4b6238ec48f1603de0bcc30489.json(1).txt](https://github.com/Thomas55555/husqvarna_automower/files/12067366/config_entry-husqvarna_automower-8fc96a4b6238ec48f1603de0bcc30489.json.1.txt)
2. During mowing: [config_entry-husqvarna_automower-8fc96a4b6238ec48f1603de0bcc30489.json(2).txt](https://github.com/Thomas55555/husqvarna_automower/files/12067375/config_entry-husqvarna_automower-8fc96a4b6238ec48f1603de0bcc30489.json.2.txt), [config_entry-husqvarna_automower-8fc96a4b6238ec48f1603de0bcc30489(3).json.txt](https://github.com/Thomas55555/husqvarna_automower/files/12067376/config_entry-husqvarna_automower-8fc96a4b6238ec48f1603de0bcc30489.3.json.txt)

The mower contiuned the normal schedule after 30 min. So, I could not save the diagnostics after the 30min option.

**Comment by Thomas55555** [comment]
okay
