### ISSUE TITLE
Map not updating - Nera models not full supported

### ISSUE THREAD

**Issue by sircoynie** [Thomas55555/husqvarna_automower#529]
I have got the integration fully working. Followed the map guide fully but don’t get any map updates for my 430x Nera mower. Anyone get any tips? Thanks

**Comment by Routout** [comment]
I have 320 Nera and it's working.

**Comment by jgorissen** [comment]
I have a 430x aswell and also have a problem after installing the newest version of this integration. The last version worked, but with this one my camera card says:
This entity is no longer being provided by the husqvarna_automower integration. If the entity is no longer in use, delete it in settings.

**Comment by Routout** [comment]
It changed to image entity at last update. Change your card accordingly.

**Comment by ChHellmann** [comment]
Alle Werte und die Position in der Karte werden neu bei Neustart von HA aktualisiert. Im Protokoll ist der Fehler: Your API-Key is not compatible to the websocket, please refresh it on https://developer.husqvarnagroup.cloud/
API Key aber korrekt eingetragen

**Comment by TheLordVader** [comment]
> I have got the integration fully working. Followed the map guide fully but don’t get any map updates for my 430x Nera mower. Anyone get any tips? Thanks

I have a 430X NERA as well and as far as I can see (installed the add-on today) the map IS NOT updating.
