### ISSUE TITLE
The Calendar entity kills the mobile Home Assistant Calendar

### ISSUE THREAD

**Issue by Someguitarist** [Thomas55555/husqvarna_automower#533]
**Prerequirements**
[X ] I have connected my mower(s) to the Automower Connect App
[X ] I have connected my Husqvanra developers account to the Authentication API
[X ] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
For the longest time both the IOS and Android version of Home Assistant's Calendar sidebar would soft-lock the app every time it was opened.  My automower went down due to lightning and it looks like now that the mower calendar isn't provided the calendar now loads.

Probably more of a Home Assistant app but than anything else, but just fyi as I've opened a ticket with them as well suggesting to truncate the calendar data after a month or so.

Sidenote:  Everything else worked wonderfully with this addon while my mower was alive, so thanks for that!

**Comment by Thomas55555** [comment]
There is indeed a bug in the calendar, but it never crashed the app for me. The problem ist, when the calendar is opened, the entity looks for the current address of the mower. This may take some time and should actually be done in the dataupdatecoordinator
Did I understand it right, that your calendar entries are still there? And you have deleted the integration?

**Comment by Someguitarist** [comment]
Gotcha, that's really interesting!  So I haven't deleted the integration as I'm hoping they'll have the mower back and fixed one day.  But at the moment it shows up as unavailable.  Then it looks like when it's unavailable it isn't providing the calendar entry, and then my calendar works on mobile.  

Your solution makes sense too.  Maybe it wasn't looking for the location and the location couldn't be provided causing it to lock up?  

When I get my mower back, I'll plug it in and do some more testing.  It looks like it's more of an issue with HA then anything else, honestly, I just figured I'd mention it.

**Comment by Someguitarist** [comment]
Hi,

Just to follow up on this topic, I just got my mower back, and again the calendar for the motor kills the ability to use the calendar on the mobile apps for Home Assistant.  I've tried disabling the calendar entity for the automower, but it's still stopping the regular calendar from working.

Any advice?  Anything else I can do to test?  At the moment, I'm going to have to completely disable this integration to have the calendar working again on mobile.

Thanks for all your help and hard work!  This integration has worked great, minus this one issue!

**Comment by Thomas55555** [comment]
Can you install the integration again, enable debugging for the integration, and crash the app by purpose?
After that please share the debug logfile. Maybe I can see anything there.

**Comment by Thomas55555** [comment]
Is this resolved now?
Have a look at version 2023.10.0, please.

**Comment by Someguitarist** [comment]
Oh man, I'm so sorry, somehow I missed this!  It was working for me once I removed the automower's Calendar entity from Home Assistant.  I put the lawn mower away for the winter already, but there's a couple spots I might plug it back it to have it do on a warm day and I can check it out then.
