### ISSUE TITLE
Support for new entity type HA 2023.9

### ISSUE THREAD

**Issue by pascalwinters** [Thomas55555/husqvarna_automower#541]
**Describe the bug**
Is it possible to implement the new entity type `lawn mower`

**Expected behavior**
https://www.home-assistant.io/blog/2023/09/06/release-20239/#lawn-mower

**Comment by Thomas55555** [comment]
See #538

**Comment by pascalwinters** [comment]
So your migrating it to core. I think it's a good choice. I hope it will make the next release.
