### ISSUE TITLE
Migrating integration from Vacuum entity to Lawn Mower ?

### ISSUE THREAD

**Issue by macfr76** [Thomas55555/husqvarna_automower#542]
Home Assistant 2023.9 introduced a new type of entity to officially support Lawn Mower with a dedicated integration.
https://www.home-assistant.io/integrations/lawn_mower/

So, it's not relevant anymore to use vacuum entity for this integration.

Are you planning to migrate to this new behavior ?

**Comment by Thomas55555** [comment]
Duplicate to #541
