### ISSUE TITLE
error after HA update to 2023.11.0 : not authorized

### ISSUE THREAD

**Issue by eddysteurs** [Thomas55555/husqvarna_automower#551]
**Prerequirements**
[ ] I have connected my mower(s) to the Automower Connect App
[ ] I have connected my Husqvanra developers account to the Authentication API
[ ] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
after upgrading HA to 2023.11.0 mower became "unavailable', error log is
****************************************************************************************
"Logger: aioautomower.rest
Source: runner.py:188
First occurred: 2 November 2023 at 16:25:14 (199 occurrences)
Last logged: 09:05:51

Response mower data: {'message': 'Unauthorized'}"
***************************************************************************************
Performed rollback HA tot 2023.10.5 and it became available again.
Performed upgrade HA again to 2023.11.0 and Mower became again unavailable

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Schaka17** [comment]
Hello, same problem here.
HA version on my system is now 2023.11.1 and it does not work since v. 2023.10.5.
I hope you can fix it with an update?
Thanks for you great job and nice addon.

**Comment by kalhimeo** [comment]
Hi, just to confirm that I have the same problem, hopefully the developer will find a solution :-)
Thank you for this nice integration.

**Comment by Schaka17** [comment]
Actually Core 2023.11.2 is installed, nothing better. Every update the app ask me i had to reconfigure the integration. If i had do it, its the same problem as before.

**Comment by kalhimeo** [comment]
somehow I managed to have mine working again. I just run through all the setup steps again one by one and it worked, although I feel like I also did that without success in the past :p

**Comment by eddysteurs** [comment]
indeed, removed both integration and application secret and did full reinstall and now it is working again

**Comment by eddysteurs** [comment]
fixed by uninstall and reinstall
