### ISSUE TITLE
No entity created, IndexError: list index out of range

### ISSUE THREAD

**Issue by CreateYourAccount-username** [Thomas55555/husqvarna_automower#554]
**Prerequirements**
[✅] I have connected my mower(s) to the Automower Connect App
[✅] I have connected my Husqvanra developers account to the Authentication API
[✅] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
On installing the integration I have no errors. Then when the install completes I have the Husqvarna Automower integration, but it does not create a device/entity.

When I click on CONFIGURE I get `ERROR: Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble`

**Expected behavior**
I expected the device to be created.

**Screenshots**
<img width="568" alt="image" src="https://github.com/Thomas55555/husqvarna_automower/assets/79326884/0f7226d5-f6c0-4d9f-acc8-cb56128adb36">
<img width="434" alt="image" src="https://github.com/Thomas55555/husqvarna_automower/assets/79326884/378d90a6-1921-4e4c-912e-4afc333bc37b">

**Additional context**
I have had this integration up and running in the past. But when I got the reauthenticate error months ago I could not fix it and deleted it. So currently I am trying to reinstall. I cannot find any entities left over from the previous install. I have removed the integration and rebooted a few times to no avail. Also when the integration was removed I made sure the credentials were deleted. Also made sure all files were deleted from custom_components dir. With the current install I also tried to remove the credentials and configure again to no avail.
Curl check as described on Husqvarna Developer Portal works correctly.

Enabled debug logging with following result:
```
Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:403
First occurred: 21:01:04 (1 occurrences)
Last logged: 21:01:04

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 213, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 255, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1868, in async_create_flow
    return handler.async_get_options_flow(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/husqvarna_automower/config_flow.py", line 114, in async_get_options_flow
    return OptionsFlowHandler(config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/husqvarna_automower/config_flow.py", line 177, in __init__
    self.sel_mower_id = self.mower_idx[0]["id"]
                        ~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by lachu2** [comment]
I have the same problem with my integration - it was working fine, 2 days ago entities become unavailable and I get the same error (500).

**Comment by Thomas55555** [comment]
I've tried to reproduce this. But I don't get this error. It looks for me like a server-side problem. Maybe you can try again. And if it still doesn't work ask Husqvarna, if they have an idea?

**Comment by CreateYourAccount-username** [comment]
> I've tried to reproduce this. But I don't get this error. It looks for me like a server-side problem. Maybe you can try again. And if it still doesn't work ask Husqvarna, if they have an idea?

Before I contact Husqvarna, can I just check something with you (or someone else if anyone else is reading)? My knowledge of APIs is extremely limited and have very basic knowledge of Python etc.  But with help of the API section on the Husqvarna Developer website I managed to authenticate myself and get a token. With this token I can request a list of all my mowers --> GET /mowers.  I do get a valid 200 response, but it is an empty list:

`{
  "data": []
}`

I'm assuming this is where the fault comes from as it cannot select index 0 from an empty list. 
Could you show me what your (or another) valid GET /mowers result looks like?

**Comment by Thomas55555** [comment]
Something like this:
https://github.com/Thomas55555/husqvarna_automower/blob/8c72c1a7960c5e1f984d983f2229fa1128a6d70b/custom_components/husqvarna_automower/tests/const.py#L48

What is the automower connect app showing?

**Comment by CreateYourAccount-username** [comment]
> Something like this:
> 
> https://github.com/Thomas55555/husqvarna_automower/blob/8c72c1a7960c5e1f984d983f2229fa1128a6d70b/custom_components/husqvarna_automower/tests/const.py#L48
> 
> What is the automower connect app showing?

Thanks for that. 

Connect app is working perfectly. I'll see if I can get an answer out of Husqvarna...
