### ISSUE TITLE
Problem sensor = Unknown when mowing

### ISSUE THREAD

**Issue by mkmer** [Thomas55555/husqvarna_automower#555]
**Prerequirements**
[x] I have connected my mower(s) to the Automower Connect App
[x] I have connected my Husqvanra developers account to the Authentication API
[x] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
When the mower is mowing, the problem sensor is "unknown" - all other states appear to work fine.

**Expected behavior**
I would think it would be "ok" or "mowing" or something other than unknown when mowing.
**Screenshots**

**Additional context**
from diagnostics:
         "mower": {
            "mode": "MAIN_AREA",
            "activity": "MOWING",
            "state": "IN_OPERATION",
            "errorCode": 0,
            "errorCodeTimestamp": 0
          },
I modified sensor.py to add mowing to `get_problem()` just under `==CHARGING` ln 55, add similar line with `=="MOWING"` - may or may not be "right", but problem sensor is no longer unknown when mowing.

**Comment by mkmer** [comment]
[config_entry-husqvarna_automower-e954a2e877edbdfa0c6ae28563b80c8e.json.txt](https://github.com/Thomas55555/husqvarna_automower/files/13340934/config_entry-husqvarna_automower-e954a2e877edbdfa0c6ae28563b80c8e.json.txt)

**Comment by Thomas55555** [comment]
`unknown` is actually right, because when it's knowing, it has no problem.

**Comment by mkmer** [comment]
Seems like "OK" or "No Problem" would be more clear :)  
Unknown make a user believe it's not being updated....

**Comment by Thomas55555** [comment]
So according to this `none` would be the right state, because the mower has no problem, right?

**Comment by Thomas55555** [comment]
`"none"` as a string sounds quiet okay. A saw some other integrations doing this.
