### ISSUE TITLE
Map image no longer working..

### ISSUE THREAD

**Issue by lancercncs1** [Thomas55555/husqvarna_automower#560]
**Prerequirements**
[x ] I have connected my mower(s) to the Automower Connect App
[x] I have connected my Husqvanra developers account to the Authentication API
[x] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**

Although the rest of the integration works (all my other entities describing my automower), the map image giving its placement (as it mows) no longer operates. When I click the map entity on my HA card, the following message appears:
"This entity is no longer being provided by the husqvarna_automower integration. If the entity is no longer in use, delete it in settings"

**Expected behavior**

I expected that the map image (map_image.png) would come up upon clicking the HA card showing the approximate location of my automower.

**Screenshots**

![image](https://github.com/Thomas55555/husqvarna_automower/assets/94853152/b2934bde-847a-482d-af2d-be6ede6d014c)

**Additional context**

I checked that the name of the file within the integration matches that on the HA server (map_image.png). I've used this integration for over a year. It had been working just fine before.

I am on Home Assistant Core 12.3 , Supervisor 11.6 and 11.2 OS.

Does anyone know what may be going on here? Thank you so much!

**Comment by prairiesnpr** [comment]
Did you happen to recently upgrade? The camera entity was replaced with an image entity. Check your entity list and and see if you have a map image entity.

**Comment by lancercncs1** [comment]
Yes I had recently updated! I  now notice that the entity changed. That was the problem! I changed to the new image entity and now the map works. Thank you very much prairiesnpr!

**Comment by prairiesnpr** [comment]
Issue resolved.
