### ISSUE TITLE
Will not load in HA 2024.0b1

### ISSUE THREAD

**Issue by m7r** [Thomas55555/husqvarna_automower#566]
**Prerequirements**
[x] I have connected my mower(s) to the Automower Connect App
[x] I have connected my Husqvanra developers account to the Authentication API
[x] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
In HA 2024.2.b1 the integration will not load.

**Expected behavior**
Integration will load in python 3.12

**Screenshots**

**Additional context**
Setup failed for custom integration 'husqvarna_automower': Requirements for husqvarna_automower not found: ['Shapely>=1.8.2'].

**Comment by Thomas55555** [comment]
For me it's working with that version in the development environment and worth python 3.12.
Are you using docker?

**Comment by m7r** [comment]
I am running Homeassistant OS 11.4 on a raspberry Pi.
Even Update to latest rc has same error.
Core
2024.2.0b3
Supervisor
2024.01.1
Operating System
11.5.rc3
Frontend
20240202.0

**Comment by m7r** [comment]
After installation of Core 2024.2.0b5 integration loads normally.
