### ISSUE TITLE
The app reports "Städar" aso. in Swedish

### ISSUE THREAD

**Issue by Segran** [Thomas55555/husqvarna_automower#68]
Where can I correct "Städar" to "Klipper" or how do I keep the English strings?

**Comment by Thomas55555** [comment]
From version 2021.4.0 I decided to use the standard vacuum states. And the standard state for operating a vacuum is "cleaning/städar". This gives some benefits in the UI. An alternative would be to introduce a mower platform in HA. Than the states would better fit to a mower. Maybe you can discuss this somewhere.
The english string is cleaning, too.
