### ISSUE TITLE
Error with the new HACS integration : No matching distribution found for husqvarna-automower==0.5

### ISSUE THREAD

**Issue by kalhimeo** [Thomas55555/husqvarna_automower#7]
Dear Thomas,

I installed your module via the new HACS method, and I am facing an error when trying to add the HA integration. I get the following error in the HA log :

`Unable to install package husqvarna-automower==0.5: ERROR: Could not find a version that satisfies the requirement husqvarna-automower==0.5 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5.17) ERROR: No matching distribution found for husqvarna-automower==0.5`

Thanks for your work !

**Comment by Thomas55555** [comment]
Hi,
that's right, please try to install v0.6.1. Should be fixed there.

**Comment by kalhimeo** [comment]
it s fixed , thank you !
