### ISSUE TITLE
API GPS Positions

### ISSUE THREAD

**Issue by Robinini** [Thomas55555/husqvarna_automower#78]
Hi - today checked my API response Log and there are now latitude and longitude positions for a mower, eg: (anonymized)

```
"metadata":{
    "connected":true,
    "statusTimestamp":1624605838531
 },
 "positions":[
    {
       "latitude":47.xxxxx,
       "longitude":8.xxxxx
    },
    {
       "latitude":47.xxxxx,
       "longitude":8.xxxxx
    }, ...
 ],
```

Thought you might want to check this out....

**Comment by Nordicfastware** [comment]
Oh great, that was what was missing in this API ! I would also be very interested in having that integrated to a device_tracker entity !

**Comment by Robinini** [comment]
There are quite a few positions, enough for a recent path, which could be stored. Possibly 5 minutes worth - enough to span the refresh (if I understood your meaning…)
