### ISSUE TITLE
Device tracker problem

### ISSUE THREAD

**Issue by TPochobradsky** [Thomas55555/husqvarna_automower#84]
Hi,
I have connected two automower to your integration, one at home and second at the cottage. There was a problem after the update "Platform husqvarna_automower does not generate unique IDs."
Could you check debug report to see if you find a issue?
Thank you for your help
Tomas

[Debug.txt](https://github.com/Thomas55555/husqvarna_automower/files/6849887/Debug.txt)

**Comment by Thomas55555** [comment]
I haven't the possibility to test it with to mowers, maybe there is a bug. Give me some days to figure it out.

**Comment by Thomas55555** [comment]
There was a stupid mistake in the code, so it was quite easy to discover. Can you please test 2021.7.0b0 of this component? You have to delete the old device_tracker entity afterwards.

**Comment by TPochobradsky** [comment]
Thank you for quick solution. I have used new version and for first view all is perfect. :-) I will tested it next days and till end of week I send you final result.
Tomas

[Debug new.txt](https://github.com/Thomas55555/husqvarna_automower/files/6858755/Debug.new.txt)

**Comment by TPochobradsky** [comment]
Tested version is without fault. Thank you very much.
Tomas
