### ISSUE TITLE
Feature Request: Refresh button

### ISSUE THREAD

**Issue by 0rTiN** [Thomas55555/husqvarna_automower#88]
Could you implement a refresh button. It could be helpful if you need the current state and don't want to wait for the next 5 minute intervall request.

**Comment by Thomas55555** [comment]
Hello.
Maybe it's better using this.
```
service: homeassistant.update_entity
target:
  entity_id: vacuum.automower_r_xxxxx
```

**Comment by 0rTiN** [comment]
Hi and thx,
haven't know this yet, I am new to HA.

Works perfect. Thx again!

**Comment by Thomas55555** [comment]
You're welcome.
Thanks for the coffee.
