### ISSUE TITLE
429 Error

### ISSUE THREAD

**Issue by nelsonblaha** [Thomas55555/husqvarna_automower#89]
Getting this in HA logs on startup:

`Error requesting husqvarna_automower data: 429, message='', url=URL('https://api.amc.husqvarna.dev/v1/mowers/')`

429 is 'too many requests', isn't it? Anyone else having this? I've only installed this integration as directed, not sure why I'd have more requests than anyone else.

**Comment by Thomas55555** [comment]
I've never had this problem before. Do you have automations, which trigger on startup?
For more details, you can activate debugging, and check, if there are a lot if requests on startup.

**Comment by nelsonblaha** [comment]
I've looked around for anything that could be polling it extra. I found none, and never wrote any. I was a little suspicious of the duplicate automower entity that was created last time I needed to re-authorize, so I deleted the integration and started over. No automowers or error messages appear now :-(

**Comment by simontegelid** [comment]
This should be fixed in #102, feel free to test it before merging.
