### ISSUE TITLE
Model of mover shows "unavailable" instead of the model name

### ISSUE THREAD

**Issue by 0rTiN** [Thomas55555/husqvarna_automower#98]
Hi,
as I can see there was an update, seems this causes for me that the model of my mover, which is an 315x, gets not correct shown anymore. Instead "Unavailable" is shown.

![image](https://user-images.githubusercontent.com/31847182/131459878-700143e6-8b27-4d23-ba2c-d57d2ad8cc50.png)

Its not a technical issue, but could you try to fix it?

**Comment by Thomas55555** [comment]
Can you send me a debug log? Just this part: ```2021-09-23 18:43:47 DEBUG (MainThread) [custom_components.husqvarna_automower] Mower data: {'data': [{'type': 'mower', 'id': 'b2bc3443-xxxx-4c7f-834e-d6e408c53f1b', 'attributes': {'system': {'name': 'Haffi', 'model': 'HUSQVARNA AUTOMOWER® 315X',```

As reported here (https://github.com/walthowd/ha-automower/pull/23 ) the API isn't sending always the model name. But this integration is using another API. I also discovered, that some people receive a different string for the model name (https://github.com/Thomas55555/husqvarna_automower/issues/74)

**Comment by 0rTiN** [comment]
Seems to be fixed. I updated today to version 2021.9.0.

![image](https://user-images.githubusercontent.com/31847182/134729344-6015651a-9dbe-452b-aa4e-fd3c2a530d74.png)
